package xyz.block.trailblaze.host

import java.io.File
import java.nio.file.Files
import java.nio.file.Path
import xyz.block.trailblaze.bundle.WorkspaceClientDtsGenerator
import xyz.block.trailblaze.config.project.PackSource
import xyz.block.trailblaze.config.project.ResolvedPack
import xyz.block.trailblaze.util.Console

/**
 * Per-pack tsconfig + gitignore emitter — the framework-owned, author-invisible
 * companion to [PerPackClientDtsEmitter].
 *
 * Each filesystem-backed pack gets:
 *   1. `<packDir>/tools/tsconfig.json` — a **self-contained** framework-bannered file
 *      that carries every compiler option inline (no `extends:` chain) and a `paths`
 *      mapping that resolves `@trailblaze/scripting` against the workspace SDK
 *      declaration bundle at a computed relative path. The TS language server picks up
 *      the `client.d.ts` declaration-merge surface and authors get typed
 *      `client.tools.<name>(args)` autocomplete in both `.ts` and `.js` tool sources
 *      (`allowJs: true` is inlined too). Authors do not edit this file — the banner at
 *      the top labels it as framework-generated.
 *   2. `<packDir>/.gitignore` — ensures the two framework artifact paths under
 *      `tools/` are ignored by `git status` (`tools/tsconfig.json` and
 *      `tools/.trailblaze/`). Appended to any existing `.gitignore`; existing
 *      entries are not duplicated.
 *
 * **Why self-contained (no `extends:`) — the npm-portability invariant.** A
 * trailmap published as an npm package and installed into a different workspace's
 * `node_modules/` must still type-check. Before Phase-D, the per-pack tsconfig
 * `extends:`-ed a workspace `tsconfig.base.json` that the framework wrote at a known
 * relative depth — that chain breaks the moment the pack is moved. With every compiler
 * option inlined, the only workspace-relative reference is the `paths` mapping pointing
 * at the SDK declaration bundle, and **this emitter re-derives that `paths` entry on
 * every `trailblaze compile`** — so a pack vendored at a new depth (or copied from
 * `node_modules/` into a different workspace) gets a correctly-computed relative path
 * on its next compile without any manual intervention. The bundle itself is shipped
 * pre-built in the framework JAR and only *extracted* to the workspace by
 * [WorkspaceTypeScriptSetup]; bundle regeneration is a separate manual operation
 * (`./gradlew :trailblaze-models:bundleTrailblazeSdkDts`) for SDK contributors. See
 * the consuming devlog `docs/devlog/2026-05-12-npm-distribution-for-trailmaps.md`.
 *
 * **Why a .gitignore at the pack root rather than relying on a top-level repo
 * ignore?** Packs are portable. A pack that lives inside a workspace whose top-level
 * `.gitignore` already covers the per-pack `tools/.trailblaze/` artifact doesn't
 * need this — but a pack vendored into a different repository (or a workspace that
 * chose not to inherit the repo-wide ignore) still gets clean `git status` by
 * default. The duplicate cost of two-line entries in a pack's gitignore is trivial
 * compared to the support burden of authors who don't know why their tsconfig keeps
 * appearing in `git status`.
 *
 * **Discoverability constraint.** The tsconfig MUST live at `<packDir>/tools/` — the
 * TypeScript language server walks UP from an open `.ts` file looking for the
 * nearest tsconfig, so the file cannot hide inside `.trailblaze/`. Authors don't
 * have to look at it (it's in `.gitignore`), but the LS does.
 *
 * **Idempotency.** Both writes are content-hash compared before write: if the
 * existing bytes match what we're about to emit, the file is left alone. Keeps
 * mtimes stable so IDE TS server caches and file watchers don't churn on no-op
 * `trailblaze compile` runs.
 *
 * **Banner-gated overwrite — the upgrade-safety contract.** Pre-1.x workspaces
 * shipped a hand-authored `tools/tsconfig.json`. This emitter MUST NOT silently
 * destroy those overrides on the first compile after upgrade. The rule is:
 *
 *   - If the existing file is missing OR carries the [FRAMEWORK_BANNER] string,
 *     it's framework-owned: rewrite freely.
 *   - If the existing file is hand-authored (anything else), preserve it verbatim
 *     and emit a one-line `Console.error` per pack telling the author to delete
 *     the file and re-run `trailblaze compile` to pick up the framework-generated
 *     version.
 *
 * Classpath-backed packs are skipped — they live inside JARs and can't accept
 * written files. Their consumers still get typed bindings through the workspace
 * packs that depend on them (transitive exports surface via
 * [PerPackClientDtsEmitter]).
 *
 * Failure handling follows the convention set by [PerPackClientDtsEmitter] and
 * [WorkspaceTypeScriptSetup]: this helper throws on IO errors; the CLI's
 * `trailblaze compile` lets exceptions propagate (fail-fast) while the daemon-init
 * bootstrap downgrades to a warning so codegen failure doesn't take the daemon
 * down with it.
 */
object PerPackTsconfigEmitter {

  /**
   * Emit `tools/tsconfig.json` + pack-root `.gitignore` for every filesystem-backed
   * pack in [resolvedPacks]. Returns the absolute paths of every file the emitter
   * is responsible for (both files per pack, even when an individual write was a
   * no-op because the on-disk content already matched). Authors of preserved
   * hand-written tsconfigs get a per-pack [Console.error] explaining the upgrade
   * path; the file path is still returned so caller logs reflect a stable count.
   *
   * @param workspaceRoot the workspace's `trails/` directory — the same root
   *   [WorkspaceTypeScriptSetup.setUp] writes `.trailblaze/sdk/dist/index.d.ts` into.
   *   The generated tsconfig's `paths` entry is computed relative to this root.
   * @throws IllegalStateException if the workspace's `.trailblaze/sdk/dist/index.d.ts`
   *   doesn't exist on disk — emitting per-pack tsconfigs that point at a missing
   *   SDK bundle would only surface as cryptic IDE errors days later, so we fail loud
   *   here. Callers either let [WorkspaceTypeScriptSetup.setUp] succeed first (CLI
   *   path) or downgrade this exception to a warning (daemon-init path).
   */
  fun emit(workspaceRoot: Path, resolvedPacks: List<ResolvedPack>): List<Path> {
    if (resolvedPacks.isEmpty()) return emptyList()
    val absoluteWorkspaceRoot = workspaceRoot.toAbsolutePath().normalize()
    val sdkDtsBundleAbsolute = absoluteWorkspaceRoot
      .resolve(WorkspaceTypeScriptSetup.GENERATED_DIR_NAME)
      .resolve(WorkspaceTypeScriptSetup.SDK_DIR_NAME)
      .resolve(WorkspaceTypeScriptSetup.SDK_DTS_BUNDLE_RELATIVE_PATH)
      .normalize()
    check(Files.isRegularFile(sdkDtsBundleAbsolute)) {
      "PerPackTsconfigEmitter: workspace SDK declaration bundle not found at " +
        "$sdkDtsBundleAbsolute. Run `trailblaze check` (or restart the daemon) so " +
        "WorkspaceTypeScriptSetup.setUp can extract the SDK before per-pack tsconfigs " +
        "are emitted."
    }

    val written = mutableListOf<Path>()
    resolvedPacks.forEach { pack ->
      val packDir = (pack.source as? PackSource.Filesystem)?.packDir ?: return@forEach
      val packDirPath = packDir.toPath().toAbsolutePath().normalize()
      val toolsDir = packDirPath.resolve(TOOLS_SUBDIR)

      val tsconfigPath = toolsDir.resolve(TSCONFIG_FILENAME)
      val gitignorePath = packDirPath.resolve(GITIGNORE_FILENAME)

      val relativeSdkBundle = computeRelativePath(toolsDir, sdkDtsBundleAbsolute)
      val tsconfigContent = renderTsconfig(relativeSdkBundle)

      writeTsconfigIfFrameworkOwned(tsconfigPath, tsconfigContent, pack.manifest.id)
      ensureGitignoreEntries(gitignorePath)

      written.add(tsconfigPath)
      written.add(gitignorePath)
    }
    return written
  }

  /**
   * Compute the POSIX-style relative path from [toolsDir] to [target]. The result is
   * what the generated tsconfig's `paths` entry carries — and deliberately uses `/`
   * separators even on Windows, because tsconfig path resolution is platform-neutral
   * (the tsc binary normalizes both directions).
   *
   * Both paths are normalized first so `..` segments or duplicate separators in the
   * inputs collapse before [Path.relativize] computes the delta. The pack loader
   * already canonicalizes [PackSource.Filesystem.packDir] today, but the defensive
   * normalize keeps this helper independently correct for tests that construct paths
   * by string-concatenation.
   */
  internal fun computeRelativePath(toolsDir: Path, target: Path): String {
    val from = toolsDir.toAbsolutePath().normalize()
    val to = target.toAbsolutePath().normalize()
    val rel = from.relativize(to).toString()
    return rel.replace(File.separatorChar, '/')
  }

  /**
   * Render the per-pack tsconfig — fully self-contained. The only piece that varies
   * pack-to-pack is the SDK bundle's relative path, which adapts to the pack's depth
   * relative to the workspace root.
   *
   * The [FRAMEWORK_BANNER] line is the same shape as [WorkspaceClientDtsGenerator]'s
   * `client.d.ts` banner — an author opening this file should immediately see they
   * are looking at framework output, not authored source. The banner string is
   * ALSO load-bearing as the upgrade-safety marker — see the kdoc on the
   * containing object for details.
   *
   * **`compilerOptions` shape — load-bearing.** `target: ES2022` + `lib: ["ES2022"]`
   * matches what the SDK declaration bundle assumes (the bundle is itself pure
   * declarations, so it doesn't need DOM / Node ambient types — zod's transitive
   * types are inlined into the bundle and any `globalThis` references are guarded
   * with `typeof globalThis extends { ... } ? ... : never` patterns that gracefully
   * degrade). `moduleResolution: "Bundler"` is the TS 5.0+ resolution mode that
   * resolves `paths` relative to the defining tsconfig (no `baseUrl` needed — TS5101
   * deprecated `baseUrl` in TS 5.x and removed it in TS 7.0). `allowJs: true`
   * lights up typing for `.js` tool sources (e.g. the `ios-contacts` example's JS
   * authoring path). `strict: true` + `esModuleInterop: true` + `skipLibCheck: true`
   * are the same baseline the prior workspace `tsconfig.base.json` carried.
   *
   * **`include` glob.** Covers all `.ts` AND `.js` files recursively (so JS-authoring
   * packs get the same typed `@trailblaze/scripting` path-mapping), plus the
   * `.trailblaze/` codegen directory so the generated `client.d.ts` declaration-merge
   * surface is picked up.
   *
   * **`exclude` of `*.test.ts`.** Mirrors the SDK's own `tsconfig.json` exclusion:
   * test files import `bun:test` (resolved natively by bun, but unknown to plain `tsc`
   * without `@types/bun` on disk) and consume the mock client returned by
   * `@trailblaze/scripting/testing`'s `createMockClient` — a `MockTrailblazeClient` whose
   * `TrailblazeToolMap` lives inside the standalone `dist/testing.d.ts` bundle and is
   * therefore distinct from (and not augmented by) the per-pack `client.d.ts`'s
   * declaration-merged `TrailblazeToolMap`. `tsc` against the framework-emitted tsconfig
   * would flag both of those as errors even though `bun test` runs the files cleanly. The
   * real type guard for tools lives in their authored source (`*.ts`, not `*.test.ts`),
   * which is what this script exists to validate. Test files are exercised by
   * `./trailblaze test` / `bun test`, not by per-pack `tsc --noEmit`.
   */
  internal fun renderTsconfig(relativeSdkBundlePath: String): String {
    val sdkBundleDir = relativeSdkBundlePath.substringBeforeLast('/', missingDelimiterValue = ".")
    return """
      $FRAMEWORK_BANNER
      {
        "compilerOptions": {
          "target": "ES2022",
          "module": "ESNext",
          "moduleResolution": "Bundler",
          "lib": ["ES2022"],
          "strict": true,
          "esModuleInterop": true,
          "skipLibCheck": true,
          "resolveJsonModule": true,
          "noEmit": true,
          "allowJs": true,
          "checkJs": false,
          "paths": {
            "@trailblaze/scripting": ["$relativeSdkBundlePath"],
            "@trailblaze/scripting/*": ["$sdkBundleDir/*"]
          }
        },
        "include": ["**/*.ts", "**/*.js", ".trailblaze/**/*"],
        "exclude": ["**/*.test.ts"]
      }
    """.trimIndent() + "\n"
  }

  /**
   * Banner-gated tsconfig writer. See the object kdoc for the contract — a
   * hand-authored tsconfig (one missing the [FRAMEWORK_BANNER] marker) is
   * preserved verbatim and the author gets a single warning per pack.
   */
  private fun writeTsconfigIfFrameworkOwned(
    tsconfigPath: Path,
    rendered: String,
    packId: String,
  ) {
    val existing = if (Files.isRegularFile(tsconfigPath)) Files.readString(tsconfigPath) else null
    if (existing == null) {
      Files.createDirectories(tsconfigPath.parent)
      Files.writeString(tsconfigPath, rendered)
      return
    }
    if (existing == rendered) return
    // Recognize the current banner OR any legacy banner (e.g. the pre-#3236 string
    // that named `trailblaze compile`) so existing on-disk tsconfigs aren't misread
    // as hand-authored after the CLI verb is renamed. First-line equality matches the
    // shape `TrailblazeCompiler.deleteOrphanOutputs` uses on the YAML side: a tsconfig
    // with the banner string buried in a hand-authored comment shouldn't be misread as
    // framework-owned just because the string appears somewhere.
    val firstLine = existing.lineSequence().firstOrNull().orEmpty()
    if (firstLine != FRAMEWORK_BANNER && firstLine !in LEGACY_FRAMEWORK_BANNERS) {
      Console.error(
        "Pack '$packId' has a hand-authored tools/tsconfig.json without the " +
          "Trailblaze framework banner — preserving it verbatim. Delete this file " +
          "and re-run `trailblaze check` to pick up the framework-managed " +
          "version with typed `client.tools.<name>(args)` autocomplete. " +
          "(Path: ${tsconfigPath.toAbsolutePath()})",
      )
      return
    }
    Files.writeString(tsconfigPath, rendered)
  }

  /**
   * Append the two pack-artifact paths to [gitignorePath] if they aren't already
   * present. Line matching uses [String.lines], which splits on `\r\n`, `\r`, or
   * `\n` and strips the terminator — so a `.gitignore` checked out on Windows
   * with CRLF endings is recognized as already containing
   * `tools/tsconfig.json` and we don't re-append on every compile (the file
   * would otherwise grow unboundedly).
   *
   * - File doesn't exist OR is blank → (re)create with both entries and the banner,
   *   no leading blank line.
   * - File exists with non-empty content and neither entry → append a separator +
   *   banner + both entries.
   * - File exists with one entry → append only the missing one with the banner.
   * - File exists with both entries → no-op.
   */
  internal fun ensureGitignoreEntries(gitignorePath: Path) {
    val existing = if (Files.isRegularFile(gitignorePath)) Files.readString(gitignorePath) else null
    val isEmpty = existing.isNullOrBlank()
    if (isEmpty) {
      Files.createDirectories(gitignorePath.parent)
      Files.writeString(gitignorePath, GITIGNORE_BLOCK_HEADER + GITIGNORE_ENTRIES_BLOCK)
      return
    }
    val existingLines = existing!!.lines().toSet()
    val missing = GITIGNORE_ENTRIES.filter { it !in existingLines }
    if (missing.isEmpty()) return
    val toAppend = buildString {
      if (!existing.endsWith('\n')) append('\n')
      append('\n')
      append(GITIGNORE_BLOCK_HEADER)
      missing.forEach { append(it).append('\n') }
    }
    Files.writeString(gitignorePath, existing + toAppend)
  }

  /** Pack-relative subdirectory the tsconfig lives under. Matches the existing
   *  [WorkspaceClientDtsGenerator.PACK_TOOLS_SUBDIR] constant. */
  internal const val TOOLS_SUBDIR: String = WorkspaceClientDtsGenerator.PACK_TOOLS_SUBDIR

  /** Generated tsconfig filename — same shape as authors would have written by hand. */
  internal const val TSCONFIG_FILENAME: String = "tsconfig.json"

  /** Pack-root gitignore filename. */
  internal const val GITIGNORE_FILENAME: String = ".gitignore"

  /**
   * Banner string used both as the human-facing "do not edit" marker on the
   * generated file AND as the framework-owned detection marker for the
   * banner-gated overwrite logic. Changing this string is an upgrade-compatibility
   * break — every pack's existing framework-generated tsconfig would then be
   * mistaken for a hand-authored override.
   */
  internal const val FRAMEWORK_BANNER: String =
    "// FRAMEWORK-GENERATED. Author should not edit. Regenerated by `trailblaze check`."

  /**
   * Banners written by previous versions of this emitter. [writeTsconfigIfFrameworkOwned]
   * treats any tsconfig whose first line matches one of these as framework-owned for
   * the purposes of the overwrite decision, so a CLI verb rename (e.g. `trailblaze
   * compile` → `trailblaze check`) doesn't strand pre-existing tsconfigs as
   * "hand-authored" overrides and produce a spurious warning. Migration window is
   * open-ended on purpose — same posture as
   * [xyz.block.trailblaze.compile.TrailblazeCompiler]'s `LEGACY_GENERATED_BANNERS`.
   */
  internal val LEGACY_FRAMEWORK_BANNERS: Set<String> = setOf(
    "// FRAMEWORK-GENERATED. Author should not edit. Regenerated by `trailblaze compile`.",
  )

  /**
   * The two paths the gitignore needs to cover, relative to the pack root.
   * Derived from the shared [WorkspaceClientDtsGenerator] constants so a rename
   * of the codegen output directory doesn't silently desynchronize the gitignore
   * — same single-source-of-truth posture as the rest of the emitter.
   */
  internal val GITIGNORE_ENTRIES: List<String> = listOf(
    "$TOOLS_SUBDIR/$TSCONFIG_FILENAME",
    "$TOOLS_SUBDIR/${WorkspaceClientDtsGenerator.GENERATED_DIR_NAME}/",
  )

  /**
   * Comment header written above the framework-managed entries. Authors don't
   * need to know the mechanics, but the comment makes a future "why is this
   * here?" question answerable from inside the file.
   */
  private const val GITIGNORE_BLOCK_HEADER: String =
    "# Trailblaze framework artifacts (regenerated by `trailblaze check`).\n"

  private val GITIGNORE_ENTRIES_BLOCK: String =
    GITIGNORE_ENTRIES.joinToString(separator = "\n", postfix = "\n")
}
