package xyz.block.trailblaze.host

import java.io.File
import java.nio.file.Files
import java.nio.file.Path
import xyz.block.trailblaze.bundle.WorkspaceClientDtsGenerator
import xyz.block.trailblaze.config.project.TrailmapSource
import xyz.block.trailblaze.config.project.ResolvedTrailmap
import xyz.block.trailblaze.util.Console

/**
 * Per-trailmap tsconfig + gitignore emitter — the framework-owned, author-invisible
 * companion to [PerTrailmapClientDtsEmitter].
 *
 * Each filesystem-backed trailmap gets:
 *   1. `<trailmapDir>/tools/tsconfig.json` — a **self-contained** framework-bannered file
 *      that carries every compiler option inline (no `extends:` chain) and a `paths`
 *      mapping that resolves `@trailblaze/scripting` against the workspace SDK
 *      declaration bundle at a computed relative path. The TS language server picks up
 *      the `trailblaze-client.d.ts` declaration-merge surface and authors get typed
 *      `client.tools.<name>(args)` autocomplete in both `.ts` and `.js` tool sources
 *      (`allowJs: true` is inlined too). Authors do not edit this file — the banner at
 *      the top labels it as framework-generated.
 *   2. `<trailmapDir>/.gitignore` — ensures the two framework artifact paths under
 *      `tools/` are ignored by `git status` (`tools/tsconfig.json` and
 *      `tools/trailblaze-client.d.ts`). Appended to any existing `.gitignore`;
 *      existing entries are not duplicated. Authors who instead want to commit
 *      either file (treat the typed surface as a checked-in API contract for
 *      clone-time IDE resolution) can — already-tracked files are unaffected.
 *
 * **Why self-contained (no `extends:`) — the npm-portability invariant.** A
 * trailmap published as an npm package and installed into a different workspace's
 * `node_modules/` must still type-check. Before Phase-D, the per-trailmap tsconfig
 * `extends:`-ed a workspace `tsconfig.base.json` that the framework wrote at a known
 * relative depth — that chain breaks the moment the trailmap is moved. With every compiler
 * option inlined, the only workspace-relative reference is the `paths` mapping pointing
 * at the SDK declaration bundle, and **this emitter re-derives that `paths` entry on
 * every `trailblaze compile`** — so a trailmap vendored at a new depth (or copied from
 * `node_modules/` into a different workspace) gets a correctly-computed relative path
 * on its next compile without any manual intervention. The bundle itself is shipped
 * pre-built in the framework JAR and only *extracted* to the workspace by
 * [WorkspaceTypeScriptSetup]; bundle regeneration is a separate manual operation
 * (`./gradlew :trailblaze-models:bundleTrailblazeSdkDts`) for SDK contributors. See
 * the consuming devlog `docs/devlog/2026-05-12-npm-distribution-for-trailmaps.md`.
 *
 * **Why a .gitignore at the trailmap root rather than relying on a top-level repo
 * ignore?** Trailmaps are portable. A trailmap that lives inside a workspace whose top-level
 * `.gitignore` already covers the per-trailmap `tools/trailblaze-client.d.ts` artifact doesn't
 * need this — but a trailmap vendored into a different repository (or a workspace that
 * chose not to inherit the repo-wide ignore) still gets clean `git status` by
 * default. The duplicate cost of two-line entries in a trailmap's gitignore is trivial
 * compared to the support burden of authors who don't know why their tsconfig keeps
 * appearing in `git status`.
 *
 * **Discoverability constraint.** The tsconfig MUST live at `<trailmapDir>/tools/` — the
 * TypeScript language server walks UP from an open `.ts` file looking for the
 * nearest tsconfig, so the file cannot hide inside `.trailblaze/`. Authors don't
 * have to look at it (it's in `.gitignore`), but the LS does.
 *
 * **Idempotency.** Both writes are content-hash compared before write: if the
 * existing bytes match what we're about to emit, the file is left alone. Keeps
 * mtimes stable so IDE TS server caches and file watchers don't churn on no-op
 * `trailblaze compile` runs.
 *
 * **Banner-gated overwrite — the upgrade-safety contract.** Pre-1.x workspaces
 * shipped a hand-authored `tools/tsconfig.json`. This emitter MUST NOT silently
 * destroy those overrides on the first compile after upgrade. The rule is:
 *
 *   - If the existing file is missing OR carries the [FRAMEWORK_BANNER] string,
 *     it's framework-owned: rewrite freely.
 *   - If the existing file is hand-authored (anything else), preserve it verbatim
 *     and emit a one-line `Console.error` per trailmap telling the author to delete
 *     the file and re-run `trailblaze compile` to pick up the framework-generated
 *     version.
 *
 * Classpath-backed trailmaps are skipped — they live inside JARs and can't accept
 * written files. Their consumers still get typed bindings through the workspace
 * trailmaps that depend on them (transitive exports surface via
 * [PerTrailmapClientDtsEmitter]).
 *
 * Failure handling follows the convention set by [PerTrailmapClientDtsEmitter] and
 * [WorkspaceTypeScriptSetup]: this helper throws on IO errors; the CLI's
 * `trailblaze compile` lets exceptions propagate (fail-fast) while the daemon-init
 * bootstrap downgrades to a warning so codegen failure doesn't take the daemon
 * down with it.
 */
object PerTrailmapTsconfigEmitter {

  /**
   * Emit `tools/tsconfig.json` + trailmap-root `.gitignore` for every filesystem-backed
   * trailmap in [resolvedTrailmaps]. Returns the absolute paths of every file the emitter
   * is responsible for (both files per trailmap, even when an individual write was a
   * no-op because the on-disk content already matched). Authors of preserved
   * hand-written tsconfigs get a per-trailmap [Console.error] explaining the upgrade
   * path; the file path is still returned so caller logs reflect a stable count.
   *
   * @param workspaceRoot the workspace's `trails/` directory — the same root
   *   [WorkspaceTypeScriptSetup.setUp] writes `.trailblaze/sdk/dist/index.d.ts` into.
   *   The generated tsconfig's `paths` entry is computed relative to this root.
   * @throws IllegalStateException if the workspace's `.trailblaze/sdk/dist/index.d.ts`
   *   doesn't exist on disk — emitting per-trailmap tsconfigs that point at a missing
   *   SDK bundle would only surface as cryptic IDE errors days later, so we fail loud
   *   here. Callers either let [WorkspaceTypeScriptSetup.setUp] succeed first (CLI
   *   path) or downgrade this exception to a warning (daemon-init path).
   */
  fun emit(workspaceRoot: Path, resolvedTrailmaps: List<ResolvedTrailmap>): List<Path> {
    if (resolvedTrailmaps.isEmpty()) return emptyList()
    val absoluteWorkspaceRoot = workspaceRoot.toAbsolutePath().normalize()
    val sdkDtsBundleAbsolute = absoluteWorkspaceRoot
      .resolve(WorkspaceTypeScriptSetup.GENERATED_DIR_NAME)
      .resolve(WorkspaceTypeScriptSetup.SDK_DIR_NAME)
      .resolve(WorkspaceTypeScriptSetup.SDK_DTS_BUNDLE_RELATIVE_PATH)
      .normalize()
    check(Files.isRegularFile(sdkDtsBundleAbsolute)) {
      "PerTrailmapTsconfigEmitter: workspace SDK declaration bundle not found at " +
        "$sdkDtsBundleAbsolute. Run `trailblaze check` (or restart the daemon) so " +
        "WorkspaceTypeScriptSetup.setUp can extract the SDK before per-trailmap tsconfigs " +
        "are emitted."
    }

    val written = mutableListOf<Path>()
    resolvedTrailmaps.forEach { trailmap ->
      val trailmapDir = (trailmap.source as? TrailmapSource.Filesystem)?.trailmapDir ?: return@forEach
      val trailmapDirPath = trailmapDir.toPath().toAbsolutePath().normalize()
      val toolsDir = trailmapDirPath.resolve(TOOLS_SUBDIR)

      val tsconfigPath = toolsDir.resolve(TSCONFIG_FILENAME)
      val gitignorePath = trailmapDirPath.resolve(GITIGNORE_FILENAME)

      val relativeSdkBundle = computeRelativePath(toolsDir, sdkDtsBundleAbsolute)
      val tsconfigContent = renderTsconfig(relativeSdkBundle)

      writeTsconfigIfFrameworkOwned(tsconfigPath, tsconfigContent, trailmap.manifest.id)
      ensureGitignoreEntries(gitignorePath)

      written.add(tsconfigPath)
      written.add(gitignorePath)
    }
    return written
  }

  /**
   * Emit a `tools/tsconfig.json` under [outputBaseDir] for each trailmap id in [trailmapIds]
   * (`<outputBaseDir>/<id>/tools/tsconfig.json`). Companion to
   * [PerTrailmapClientDtsEmitter.emitClasspathValidationSurfaces] — that method writes the
   * `trailblaze-client.d.ts` into the same scratch `tools/` dir; this one writes the tsconfig
   * next to it so [TrailTscValidator] can run the bundled `tsc` against the target's typed
   * surface. Pass the exact set of ids the surface emitter produced. Returns the absolute paths
   * of every tsconfig written.
   *
   * Unlike [emit], this writes into a framework-owned scratch location (a gitignored
   * `<trails>/.trailblaze/…` subtree), so there is **no hand-authored-tsconfig preservation and
   * no `.gitignore` emission** — the tsconfig is always (over)written, and the surrounding
   * `.trailblaze/` dir is already ignored.
   *
   * @param workspaceRoot the workspace's `trails/` directory — same anchor [emit] uses to locate
   *   the SDK declaration bundle the generated `paths` entry points at.
   * @throws IllegalStateException if the workspace SDK bundle isn't on disk yet (same fail-loud
   *   contract as [emit]; callers run [WorkspaceTypeScriptSetup.setUp] first).
   */
  fun emitClasspathValidationTsconfigs(
    workspaceRoot: Path,
    trailmapIds: Collection<String>,
    outputBaseDir: Path,
  ): List<Path> {
    if (trailmapIds.isEmpty()) return emptyList()
    val absoluteWorkspaceRoot = workspaceRoot.toAbsolutePath().normalize()
    val sdkDtsBundleAbsolute = absoluteWorkspaceRoot
      .resolve(WorkspaceTypeScriptSetup.GENERATED_DIR_NAME)
      .resolve(WorkspaceTypeScriptSetup.SDK_DIR_NAME)
      .resolve(WorkspaceTypeScriptSetup.SDK_DTS_BUNDLE_RELATIVE_PATH)
      .normalize()
    check(Files.isRegularFile(sdkDtsBundleAbsolute)) {
      "PerTrailmapTsconfigEmitter: workspace SDK declaration bundle not found at " +
        "$sdkDtsBundleAbsolute. Run `trailblaze check` (or restart the daemon) so " +
        "WorkspaceTypeScriptSetup.setUp can extract the SDK before validation-surface tsconfigs " +
        "are emitted."
    }

    val written = mutableListOf<Path>()
    trailmapIds.forEach { id ->
      val toolsDir = outputBaseDir.resolve(id)
        .resolve(TOOLS_SUBDIR)
        .toAbsolutePath()
        .normalize()
      Files.createDirectories(toolsDir)
      val relativeSdkBundle = computeRelativePath(toolsDir, sdkDtsBundleAbsolute)
      val tsconfigPath = toolsDir.resolve(TSCONFIG_FILENAME)
      // Framework-owned scratch file — always overwrite (no banner-gated preservation).
      Files.writeString(tsconfigPath, renderTsconfig(relativeSdkBundle))
      written.add(tsconfigPath)
    }
    return written
  }

  /**
   * Compute the POSIX-style relative path from [toolsDir] to [target]. The result is
   * what the generated tsconfig's `paths` entry carries — and deliberately uses `/`
   * separators even on Windows, because tsconfig path resolution is platform-neutral
   * (the tsc binary normalizes both directions).
   *
   * Both paths are normalized first so `..` segments or duplicate separators in the
   * inputs collapse before [Path.relativize] computes the delta. The trailmap loader
   * already canonicalizes [TrailmapSource.Filesystem.trailmapDir] today, but the defensive
   * normalize keeps this helper independently correct for tests that construct paths
   * by string-concatenation.
   */
  internal fun computeRelativePath(toolsDir: Path, target: Path): String {
    val from = toolsDir.toAbsolutePath().normalize()
    val to = target.toAbsolutePath().normalize()
    val rel = from.relativize(to).toString()
    return rel.replace(File.separatorChar, '/')
  }

  /**
   * Render the per-trailmap tsconfig — fully self-contained. The only piece that varies
   * trailmap-to-trailmap is the SDK bundle's relative path, which adapts to the trailmap's depth
   * relative to the workspace root.
   *
   * The [FRAMEWORK_BANNER] line is the same shape as [WorkspaceClientDtsGenerator]'s
   * `trailblaze-client.d.ts` banner — an author opening this file should immediately see they
   * are looking at framework output, not authored source. The banner string is
   * ALSO load-bearing as the upgrade-safety marker — see the kdoc on the
   * containing object for details.
   *
   * **`compilerOptions` shape — load-bearing.** `target: ES2022` + `lib: ["ES2022"]`
   * matches what the SDK declaration bundle assumes (the bundle is itself pure
   * declarations, so it doesn't need DOM / Node ambient types — zod's transitive
   * types are inlined into the bundle and any `globalThis` references are guarded
   * with `typeof globalThis extends { ... } ? ... : never` patterns that gracefully
   * degrade). `moduleResolution: "Bundler"` is the TS 5.0+ resolution mode that
   * resolves `paths` relative to the defining tsconfig (no `baseUrl` needed — TS5101
   * deprecated `baseUrl` in TS 5.x and removed it in TS 7.0). `allowJs: true`
   * lights up typing for `.js` tool sources (e.g. the `ios-contacts` example's JS
   * authoring path). `strict: true` + `esModuleInterop: true` + `skipLibCheck: true`
   * are the same baseline the prior workspace `tsconfig.base.json` carried.
   *
   * **`include` glob.** Covers all `.ts` AND `.js` files recursively (so JS-authoring
   * trailmaps get the same typed `@trailblaze/scripting` path-mapping). The generated
   * `trailblaze-client.d.ts` declaration-merge surface lives directly under `tools/`
   * (next to author sources) and is picked up by the same recursive `.ts` include —
   * no special-case glob for the framework's output directory is needed.
   *
   * **`exclude` of `*.test.ts`.** Mirrors the SDK's own `tsconfig.json` exclusion:
   * test files import `bun:test` (resolved natively by bun, but unknown to plain `tsc`
   * without `@types/bun` on disk) and consume the mock client returned by
   * `@trailblaze/scripting/testing`'s `createMockClient` — a `MockTrailblazeClient` whose
   * `TrailblazeToolMap` lives inside the standalone `dist/testing.d.ts` bundle and is
   * therefore distinct from (and not augmented by) the per-trailmap `trailblaze-client.d.ts`'s
   * declaration-merged `TrailblazeToolMap`. `tsc` against the framework-emitted tsconfig
   * would flag both of those as errors even though `bun test` runs the files cleanly. The
   * real type guard for tools lives in their authored source (`*.ts`, not `*.test.ts`),
   * which is what this script exists to validate. Test files are exercised by
   * `./trailblaze test` / `bun test`, not by per-trailmap `tsc --noEmit`.
   */
  internal fun renderTsconfig(relativeSdkBundlePath: String): String {
    val sdkBundleDir = relativeSdkBundlePath.substringBeforeLast('/', missingDelimiterValue = ".")
    // Strip the `.d.ts` suffix so the `paths` entry is a stem rather than a literal
    // declaration file. Two consumers diverge on how they treat this entry:
    //  * `tsc` (via `moduleResolution: Bundler`) tries extensions (`.ts`, `.tsx`,
    //    `.d.ts`) against the stem and finds `dist/index.d.ts` for types.
    //  * `bun` (when running `*.test.ts` or a scripted-tool subprocess) tries `.js`
    //    against the stem and finds `dist/index.js` for runtime — the file produced
    //    by `bundleTrailblazeSdkDts`'s ESM bundle step.
    // Pointing the entry at the literal `.d.ts` (the prior shape) made bun load the
    // declaration file as a runtime module and fail with "Export named 'trailblaze'
    // not found" — the failure mode PR #3338's `contacts_ios_searchContacts`
    // documented before this fix landed.
    //
    // Defensive: `removeSuffix` silently returns the input unchanged when the
    // suffix isn't present. If a future change to
    // [WorkspaceTypeScriptSetup.SDK_DTS_BUNDLE_RELATIVE_PATH] alters the bundle's
    // extension (e.g. `.d.mts`/`.d.cts`), an unchanged stem would silently re-emit
    // a `paths` entry that still points at the type-only file — quietly regressing
    // to the pre-fix "bun loads the `.d.ts` and crashes" failure mode. Require the
    // suffix at the emit site so a layout change fails loud here instead.
    require(relativeSdkBundlePath.endsWith(".d.ts")) {
      "PerTrailmapTsconfigEmitter: expected workspace SDK bundle path to end with " +
        "'.d.ts' (got: '$relativeSdkBundlePath'). If the SDK bundle layout " +
        "changed, update the stem-stripping logic alongside " +
        "WorkspaceTypeScriptSetup.SDK_DTS_BUNDLE_RELATIVE_PATH."
    }
    val sdkBundleStem = relativeSdkBundlePath.removeSuffix(".d.ts")
    return """
      $FRAMEWORK_BANNER
      {
        "compilerOptions": {
          "target": "ES2022",
          "module": "ESNext",
          "moduleResolution": "Bundler",
          "lib": ["ES2022"],
          "strict": true,
          "esModuleInterop": true,
          "skipLibCheck": true,
          "resolveJsonModule": true,
          "noEmit": true,
          "allowJs": true,
          "checkJs": false,
          "paths": {
            "@trailblaze/scripting": ["$sdkBundleStem"],
            "@trailblaze/scripting/*": ["$sdkBundleDir/*"]
          }
        },
        "include": ["**/*.ts", "**/*.js"],
        "exclude": ["**/*.test.ts"]
      }
    """.trimIndent() + "\n"
  }

  /**
   * Banner-gated tsconfig writer. See the object kdoc for the contract — a
   * hand-authored tsconfig (one missing the [FRAMEWORK_BANNER] marker) is
   * preserved verbatim and the author gets a single warning per trailmap.
   */
  private fun writeTsconfigIfFrameworkOwned(
    tsconfigPath: Path,
    rendered: String,
    trailmapId: String,
  ) {
    val existing = if (Files.isRegularFile(tsconfigPath)) Files.readString(tsconfigPath) else null
    if (existing == null) {
      Files.createDirectories(tsconfigPath.parent)
      Files.writeString(tsconfigPath, rendered)
      return
    }
    if (existing == rendered) return
    // Recognize the current banner OR any legacy banner (e.g. the pre-#3236 string
    // that named `trailblaze compile`) so existing on-disk tsconfigs aren't misread
    // as hand-authored after the CLI verb is renamed. First-line equality matches the
    // shape `TrailblazeCompiler.deleteOrphanOutputs` uses on the YAML side: a tsconfig
    // with the banner string buried in a hand-authored comment shouldn't be misread as
    // framework-owned just because the string appears somewhere.
    val firstLine = existing.lineSequence().firstOrNull().orEmpty()
    if (firstLine != FRAMEWORK_BANNER && firstLine !in LEGACY_FRAMEWORK_BANNERS) {
      Console.error(
        "Trailmap '$trailmapId' has a hand-authored tools/tsconfig.json without the " +
          "Trailblaze framework banner — preserving it verbatim. Delete this file " +
          "and re-run `trailblaze check` to pick up the framework-managed " +
          "version with typed `client.tools.<name>(args)` autocomplete. " +
          "(Path: ${tsconfigPath.toAbsolutePath()})",
      )
      return
    }
    Files.writeString(tsconfigPath, rendered)
  }

  /**
   * Append the two trailmap-artifact paths to [gitignorePath] if they aren't already
   * present. Line matching uses [String.lines], which splits on `\r\n`, `\r`, or
   * `\n` and strips the terminator — so a `.gitignore` checked out on Windows
   * with CRLF endings is recognized as already containing
   * `tools/tsconfig.json` and we don't re-append on every compile (the file
   * would otherwise grow unboundedly).
   *
   * - File doesn't exist OR is blank → (re)create with both entries and the banner,
   *   no leading blank line.
   * - File exists with non-empty content and neither entry → append a separator +
   *   banner + both entries.
   * - File exists with one entry → append only the missing one with the banner.
   * - File exists with both entries → no-op.
   */
  internal fun ensureGitignoreEntries(gitignorePath: Path) {
    val existing = if (Files.isRegularFile(gitignorePath)) Files.readString(gitignorePath) else null
    val isEmpty = existing.isNullOrBlank()
    if (isEmpty) {
      Files.createDirectories(gitignorePath.parent)
      Files.writeString(gitignorePath, GITIGNORE_BLOCK_HEADER + GITIGNORE_ENTRIES_BLOCK)
      return
    }
    val existingLines = existing!!.lines().toSet()
    val missing = GITIGNORE_ENTRIES.filter { it !in existingLines }
    if (missing.isEmpty()) return
    val toAppend = buildString {
      if (!existing.endsWith('\n')) append('\n')
      append('\n')
      append(GITIGNORE_BLOCK_HEADER)
      missing.forEach { append(it).append('\n') }
    }
    Files.writeString(gitignorePath, existing + toAppend)
  }

  /** Trailmap-relative subdirectory the tsconfig lives under. Matches the existing
   *  [WorkspaceClientDtsGenerator.TRAILMAP_TOOLS_SUBDIR] constant. */
  internal const val TOOLS_SUBDIR: String = WorkspaceClientDtsGenerator.TRAILMAP_TOOLS_SUBDIR

  /** Generated tsconfig filename — same shape as authors would have written by hand. */
  internal const val TSCONFIG_FILENAME: String = "tsconfig.json"

  /** Trailmap-root gitignore filename. */
  internal const val GITIGNORE_FILENAME: String = ".gitignore"

  /**
   * Banner string used both as the human-facing "do not edit" marker on the
   * generated file AND as the framework-owned detection marker for the
   * banner-gated overwrite logic. Changing this string is an upgrade-compatibility
   * break — every trailmap's existing framework-generated tsconfig would then be
   * mistaken for a hand-authored override.
   */
  internal const val FRAMEWORK_BANNER: String =
    "// FRAMEWORK-GENERATED. Author should not edit. Regenerated by `trailblaze check`."

  /**
   * Banners written by previous versions of this emitter. [writeTsconfigIfFrameworkOwned]
   * treats any tsconfig whose first line matches one of these as framework-owned for
   * the purposes of the overwrite decision, so a CLI verb rename (e.g. `trailblaze
   * compile` → `trailblaze check`) doesn't strand pre-existing tsconfigs as
   * "hand-authored" overrides and produce a spurious warning. Migration window is
   * open-ended on purpose — same posture as
   * [xyz.block.trailblaze.compile.TrailblazeCompiler]'s `LEGACY_GENERATED_BANNERS`.
   */
  internal val LEGACY_FRAMEWORK_BANNERS: Set<String> = setOf(
    "// FRAMEWORK-GENERATED. Author should not edit. Regenerated by `trailblaze compile`.",
  )

  /**
   * The two paths the gitignore needs to cover, relative to the trailmap root.
   * Derived from the shared [WorkspaceClientDtsGenerator] constants so a rename
   * of the codegen output file doesn't silently desynchronize the gitignore
   * — same single-source-of-truth posture as the rest of the emitter.
   *
   * Default gitignore mode is "treat as derived output." Authors who instead
   * want to commit either file (treat the typed surface as a checked-in API
   * contract) can — already-tracked files are unaffected by these ignore rules.
   */
  internal val GITIGNORE_ENTRIES: List<String> = listOf(
    "$TOOLS_SUBDIR/$TSCONFIG_FILENAME",
    "$TOOLS_SUBDIR/${WorkspaceClientDtsGenerator.GENERATED_FILE_NAME}",
  )

  /**
   * Comment header written above the framework-managed entries. Authors don't
   * need to know the mechanics, but the comment makes a future "why is this
   * here?" question answerable from inside the file.
   */
  private const val GITIGNORE_BLOCK_HEADER: String =
    "# Trailblaze framework artifacts (regenerated by `trailblaze check`).\n" +
      "# Safe to commit this .gitignore; the files it lists are generated, not source.\n"

  private val GITIGNORE_ENTRIES_BLOCK: String =
    GITIGNORE_ENTRIES.joinToString(separator = "\n", postfix = "\n")
}
