"""MkDocs build hooks for the Trailblaze docs site.

Report-gallery placeholder filling
-----------------------------------
The Report Gallery (`docs/reports.md`) and the landing-page embed reference per-trail
report assets under `docs/report-assets/<trail>/` (`storyboard.webp`, `timeline.webp`,
`report.html`). Those are produced by CI (`trailblaze report --storyboard --webp`),
uploaded as artifacts, and fetched into the build workspace by the GitHub Pages workflow
— they are NOT committed (the per-trail dirs are gitignored), so the repo carries no
per-trail binaries.

NOTE: assets deliberately live under `docs/report-assets/`, NOT `docs/generated/` —
`docs/generated/` is owned by `:docs:generator:run` and `scripts/generate-docs-and-diff.sh`
does `rm -rf docs/generated` + a reproducibility `git diff`, so anything hand-authored or
runtime-fetched there fails CI.

To keep `mkdocs build --strict` green everywhere (local `mkdocs serve`, the PR
docs-build-check, and the deploy before/without a successful trail run), this hook fills
any MISSING per-trail asset with the single committed, reusable generic placeholder
(`docs/images/report-pending.webp`) just before the file scan. Real fetched assets always
win — the hook only creates files that don't already exist.

Runs automatically on every `mkdocs build`/`serve`; no workflow wiring or staging step
needed. Add a new trail by listing its slug in `TRAILS`.
"""

from pathlib import Path

# Trail slugs that have a gallery section. Each maps to docs/report-assets/<slug>/.
# One per platform: web (wikipedia), iOS (ios-contacts), Android (clock).
TRAILS = ["wikipedia", "ios-contacts", "clock"]

_PENDING_HTML = """<!doctype html>
<meta charset="utf-8">
<title>Trailblaze report - generating in CI</title>
<body style="font-family:Inter,-apple-system,sans-serif;max-width:42rem;margin:4rem auto;padding:0 1.5rem;color:#1b4332;line-height:1.6">
  <h1>Report generating in CI</h1>
  <p>The full interactive Trailblaze report is generated by CI and published with the
     docs site on the next push to <code>main</code>. Produce one yourself from any
     session with <code>trailblaze report --id &lt;session&gt; --output-dir out --storyboard --webp</code>.</p>
  <p><a href="https://github.com/block/trailblaze">Back to Trailblaze</a></p>
</body>
"""


def on_pre_build(config):
    """Fill missing per-trail report assets before MkDocs scans the docs dir."""
    docs_dir = Path(config["docs_dir"])
    placeholder = docs_dir / "images" / "report-pending.webp"
    if not placeholder.is_file():
        # Without the generic placeholder there's nothing to copy; let the strict build
        # surface the missing reference rather than silently skipping.
        return

    pending_bytes = placeholder.read_bytes()
    for trail in TRAILS:
        trail_dir = docs_dir / "report-assets" / trail
        trail_dir.mkdir(parents=True, exist_ok=True)
        for webp in ("storyboard.webp", "timeline.webp"):
            target = trail_dir / webp
            if not target.exists():
                target.write_bytes(pending_bytes)
        report_html = trail_dir / "report.html"
        if not report_html.exists():
            report_html.write_text(_PENDING_HTML, encoding="utf-8")
