import GenerateAndroidTrailJUnitShellsTask.Companion.renderShell
import GenerateAndroidTrailJUnitShellsTask.TestHostMode
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/**
 * Unit tests for [TrailblazeAndroidGradlePlugin]'s shell renderer + identifier validation.
 *
 * Behavior asserted (the public contract callers depend on):
 *  - Renderer output matches what a human would have hand-written for the same trail-YAML set
 *    (lets a reviewer diff the generated text against the deleted hand-written file once and trust
 *    every future generation).
 *  - Identifier validation rejects names that would compile-fail at consumer time, so the build
 *    breaks at generate-time instead of at AGP's Kotlin compile.
 *
 * Wider Gradle-task wiring (TaskKit fixture: source-set wiring, up-to-date checks against the
 * trails directory) is intentionally NOT tested here — that's covered by the consumer module's
 * actual `compileDebugAndroidTestKotlin` running green against the generated source.
 */
class TrailblazeAndroidGradlePluginTest {

  // ---- Pattern A: extending-base mode (used by downstream modules with their own base) ----

  @Test
  fun `BaseClass mode renders one-method shell matching the hand-written SquareCustomToolEvalLongTest`() {
    val rendered =
      renderShell(
        packageName = "xyz.block.trailblaze.evaluation",
        className = "SquareCustomToolEvalLongTest",
        mode = TestHostMode.BaseClass("xyz.block.trailblaze.rules.SquareTrailblazeTest"),
        methodNames = listOf("squareAddItemToCart"),
      )
    val expected =
      """
      // *** DO NOT EDIT — this file is generated by xyz.block.trailblaze.android-gradle. ***
      // Source: src/androidTest/assets/trails/SquareCustomToolEvalLongTest/*.trail.yaml — to change the test surface,
      // add / rename / remove the matching <methodName>.trail.yaml files under that directory.

      package xyz.block.trailblaze.evaluation

      import org.junit.Test
      import xyz.block.trailblaze.rules.SquareTrailblazeTest

      class SquareCustomToolEvalLongTest : SquareTrailblazeTest() {

        @Test fun squareAddItemToCart() = runFromAsset()
      }
      """.trimIndent() + "\n"
    assertEquals(expected, rendered)
  }

  @Test
  fun `BaseClass mode renders multiple @Test methods separated by a blank line`() {
    val rendered =
      renderShell(
        packageName = "xyz.block.trailblaze.evaluation",
        className = "SquareCustomToolEvalLongTest",
        mode = TestHostMode.BaseClass("xyz.block.trailblaze.rules.SquareTrailblazeTest"),
        methodNames = listOf("squareAddItemToCart", "squareInputTextRandom"),
      )
    // The shape we want: one blank line between successive @Test fun declarations, and the closing
    // brace on its own line. That matches what a human would have written and lets ktfmt no-op the
    // file (the rendered text is already in the canonical formatting).
    assertEquals(
      listOf(
        "class SquareCustomToolEvalLongTest : SquareTrailblazeTest() {",
        "",
        "  @Test fun squareAddItemToCart() = runFromAsset()",
        "",
        "  @Test fun squareInputTextRandom() = runFromAsset()",
        "}",
        "",
      ),
      rendered.lines().dropWhile { !it.startsWith("class ") },
    )
  }

  // ---- Pattern B: inline-rule mode (OSS default; matches GeneratedSampleAppTests in OSS) ----

  @Test
  fun `InlineRule mode renders shell using AndroidTrailblazeRule with explicit asset paths`() {
    // Short class + method names keep the call on one line (under the ktfmt-preferred ~95 chars).
    // The three-line-wrap branch is covered by a separate test below.
    val rendered =
      renderShell(
        packageName = "xyz.example.app",
        className = "FooLongTest",
        mode = TestHostMode.InlineRule("xyz.block.trailblaze.android.AndroidTrailblazeRule"),
        methodNames = listOf("alpha"),
      )
    val expected =
      """
      // *** DO NOT EDIT — this file is generated by xyz.block.trailblaze.android-gradle. ***
      // Source: src/androidTest/assets/trails/FooLongTest/*.trail.yaml — to change the test surface,
      // add / rename / remove the matching <methodName>.trail.yaml files under that directory.

      package xyz.example.app

      import org.junit.Rule
      import org.junit.Test
      import xyz.block.trailblaze.android.AndroidTrailblazeRule

      class FooLongTest {

        @get:Rule val rule = AndroidTrailblazeRule()

        @Test fun alpha() = rule.runFromAsset("trails/FooLongTest/alpha.trail.yaml")
      }
      """.trimIndent() + "\n"
    assertEquals(expected, rendered)
  }

  @Test
  fun `InlineRule mode wraps long single-line runFromAsset calls across three lines for ktfmt fit`() {
    // A long class + method name pushes the single-line shape past the ktfmt-preferred ~95 chars.
    // The renderer should fall back to the three-line shape (`@Test` / `fun … () =` / indented
    // call) used by the OSS sample-app generator, so spotless / ktfmt no-ops the emitted file.
    val rendered =
      renderShell(
        packageName = "xyz.example.app",
        className = "VeryLongClassNameForAnAndroidLongTestThatPushesPastNinetyFive",
        mode = TestHostMode.InlineRule("xyz.block.trailblaze.android.AndroidTrailblazeRule"),
        methodNames = listOf("aSimilarlyLongMethodName"),
      )
    assertTrue("expected three-line wrap in: $rendered") {
      rendered.contains("@Test\n") &&
        rendered.contains("fun aSimilarlyLongMethodName() =\n") &&
        rendered.contains(
          "    rule.runFromAsset(\"trails/VeryLongClassNameForAnAndroidLongTestThatPushesPastNinetyFive/aSimilarlyLongMethodName.trail.yaml\")"
        )
    }
  }

  @Test
  fun `rejects an asset directory whose name is not a valid Kotlin simple identifier`() {
    val e =
      assertFailsWith<IllegalArgumentException> {
        GenerateAndroidTrailJUnitShellsTask.validateSimpleName("123StartsWithDigit", source = "(test)")
      }
    assertEquals(
      "Invalid Kotlin identifier `123StartsWithDigit` (from (test)). Class-directory names under " +
        "`src/androidTest/assets/trails/` must be valid Kotlin simple identifiers.",
      e.message,
    )
  }

  @Test
  fun `rejects a methodName whose filename derives to an invalid Kotlin identifier`() {
    val e =
      assertFailsWith<IllegalArgumentException> {
        GenerateAndroidTrailJUnitShellsTask.validateMethodName(
          "with-dash",
          className = "SquareCustomToolEvalLongTest",
        )
      }
    assertEquals(
      "Invalid Kotlin method identifier `with-dash` (from SquareCustomToolEvalLongTest/with-dash.trail.yaml). " +
        "Each <methodName>.trail.yaml filename must produce a valid Kotlin simple identifier.",
      e.message,
    )
  }

  @Test
  fun `rejects a class-directory whose name is a Kotlin hard keyword`() {
    // `when` matches SIMPLE_NAME_REGEX but is a Kotlin hard keyword — without this check the
    // generator would emit `class when : ...` and Kotlin compile would fail downstream with a
    // confusing error pointing at the generated file instead of the directory.
    val e =
      assertFailsWith<IllegalArgumentException> {
        GenerateAndroidTrailJUnitShellsTask.validateSimpleName("when", source = "(test)")
      }
    assertEquals(
      "Invalid Kotlin identifier `when` (from (test)). `when` is a Kotlin hard keyword and " +
        "cannot be used as a class name. Rename the directory.",
      e.message,
    )
  }

  @Test
  fun `rejects a method whose filename is a Kotlin hard keyword`() {
    val e =
      assertFailsWith<IllegalArgumentException> {
        GenerateAndroidTrailJUnitShellsTask.validateMethodName("fun", className = "FooLongTest")
      }
    assertEquals(
      "Invalid Kotlin method identifier `fun` (from FooLongTest/fun.trail.yaml). `fun` is a " +
        "Kotlin hard keyword and cannot be used as a method name. Rename the file.",
      e.message,
    )
  }

  @Test
  fun `accepts a name that matches a Kotlin soft keyword (those are valid identifiers)`() {
    // Soft keywords like `by`, `get`, `set`, `field`, `catch` are valid identifiers in Kotlin and
    // intentionally NOT in the hard-keyword reject set. A trail file named `by.trail.yaml` should
    // produce `@Test fun by() = runFromAsset()` without complaint.
    GenerateAndroidTrailJUnitShellsTask.validateMethodName("by", className = "FooLongTest")
    GenerateAndroidTrailJUnitShellsTask.validateMethodName("get", className = "FooLongTest")
    GenerateAndroidTrailJUnitShellsTask.validateMethodName("field", className = "FooLongTest")
  }

  @Test
  fun `rejects a single underscore as a class or method name`() {
    // `_` matches SIMPLE_NAME_REGEX (one underscore = valid identifier per the regex) and is NOT
    // a Kotlin hard keyword, so the existing checks let it through. Kotlin 1.5+ reserves `_` for
    // anonymous bindings (lambda params, destructuring), so a generated class or method named `_`
    // is almost certainly unintended.
    assertFailsWith<IllegalArgumentException> {
      GenerateAndroidTrailJUnitShellsTask.validateSimpleName("_", source = "(test)")
    }.also {
      assertEquals(
        "Invalid Kotlin identifier `_` (from (test)). `_` is reserved in Kotlin for anonymous " +
          "bindings — rename the directory to a meaningful test-class name.",
        it.message,
      )
    }
    assertFailsWith<IllegalArgumentException> {
      GenerateAndroidTrailJUnitShellsTask.validateMethodName("_", className = "FooLongTest")
    }
  }

  @Test
  fun `accepts a valid Kotlin package name`() {
    GenerateAndroidTrailJUnitShellsTask.validatePackageName("xyz.block.trailblaze.evaluation")
    GenerateAndroidTrailJUnitShellsTask.validatePackageName("a")
    GenerateAndroidTrailJUnitShellsTask.validatePackageName("a.b.c")
    // Underscores + mixed case are syntactically legal (style aside).
    GenerateAndroidTrailJUnitShellsTask.validatePackageName("_root.subPkg")
  }

  @Test
  fun `rejects malformed package names that would generate broken Kotlin`() {
    listOf(
      "",
      "123abc", // leading digit
      "a..b", // empty segment between dots
      ".leading",
      "trailing.",
      "has-dash.x", // dash is illegal in Kotlin/Java identifiers
    ).forEach { bad ->
      assertFailsWith<IllegalArgumentException>("expected `$bad` to be rejected") {
        GenerateAndroidTrailJUnitShellsTask.validatePackageName(bad)
      }
    }
  }

  @Test
  fun `rejects a baseClassFqn that historically slipped past the contains-dot check`() {
    // The original validation was a plain `contains('.')` — `"xyz."` passed it, then
    // `substringAfterLast('.')` returned "" and the renderer emitted `class X : () {`, a Kotlin
    // compile error pointing at the generated file. Lock the strengthened FQN regex against these
    // shapes.
    listOf(
      "NoDot",
      "xyz.", // trailing dot — the historical bug
      ".xyz",
      "xyz..Bar",
      "1xyz.Bar", // leading digit in first segment
      "xyz.1Bar",
      "",
    ).forEach { bad ->
      assertFailsWith<IllegalArgumentException>("expected `$bad` to be rejected") {
        GenerateAndroidTrailJUnitShellsTask.validateBaseClassFqn(bad)
      }
    }
  }

  @Test
  fun `accepts a well-formed fully qualified base class name`() {
    GenerateAndroidTrailJUnitShellsTask.validateBaseClassFqn(
      "xyz.block.trailblaze.rules.SquareTrailblazeTest"
    )
    // Two segments is the minimum (one dot required).
    GenerateAndroidTrailJUnitShellsTask.validateBaseClassFqn("a.B")
  }
}
