import GenerateAndroidTrailJUnitShellsTask.Companion.renderShell
import GenerateAndroidTrailJUnitShellsTask.TestHostMode
import GenerateAndroidTrailJUnitShellsTask.TrailMethod
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertFalse
import kotlin.test.assertTrue

/**
 * Unit tests for [TrailblazeAndroidGradlePlugin]'s shell renderer + identifier validation.
 *
 * Behavior asserted (the public contract callers depend on):
 *  - Renderer output matches what a human would have hand-written for the same trail-YAML set
 *    (lets a reviewer diff the generated text against the deleted hand-written file once and trust
 *    every future generation).
 *  - Identifier validation rejects names that would compile-fail at consumer time, so the build
 *    breaks at generate-time instead of at AGP's Kotlin compile.
 *
 * Wider Gradle-task wiring (TaskKit fixture: source-set wiring, up-to-date checks against the
 * trails directory) is intentionally NOT tested here — that's covered by the consumer module's
 * actual `compileDebugAndroidTestKotlin` running green against the generated source.
 */
class TrailblazeAndroidGradlePluginTest {

  private fun namedTrail(className: String, methodName: String) =
    TrailMethod(
      methodName = methodName,
      isRecordingDir = false,
      source = "$className/$methodName.trail.yaml",
    )

  private fun recordingDirTrail(className: String, methodName: String) =
    TrailMethod(
      methodName = methodName,
      isRecordingDir = true,
      source = "$className/$methodName/trail.yaml",
    )

  // ---- Pattern A: extending-base mode (used by downstream modules with their own base) ----

  @Test
  fun `BaseClass mode renders one-method shell matching the hand-written SquareCustomToolEvalLongTest`() {
    val rendered =
      renderShell(
        packageName = "xyz.block.trailblaze.evaluation",
        className = "SquareCustomToolEvalLongTest",
        mode = TestHostMode.BaseClass("xyz.block.trailblaze.rules.SquareTrailblazeTest"),
        methods = listOf(namedTrail("SquareCustomToolEvalLongTest", "squareAddItemToCart")),
      )
    val expected =
      """
      // *** DO NOT EDIT — this file is generated by xyz.block.trailblaze.android-gradle. ***
      // Source: src/androidTest/assets/trails/SquareCustomToolEvalLongTest/ — to change the test surface, add /
      // rename / remove the matching <methodName>.trail.yaml files or <methodName>/trail.yaml
      // recording directories under that directory.

      package xyz.block.trailblaze.evaluation

      import org.junit.Test
      import xyz.block.trailblaze.rules.SquareTrailblazeTest

      class SquareCustomToolEvalLongTest : SquareTrailblazeTest() {

        @Test fun squareAddItemToCart() = runFromAsset()
      }
      """.trimIndent() + "\n"
    assertEquals(expected, rendered)
  }

  /**
   * A module whose trails are staged in from elsewhere (a build script syncs a committed
   * `trails/<subtree>/` into the assets tree) must not have its generated header point at
   * `src/androidTest/assets/trails` — that directory holds nothing, and naming it re-teaches the
   * layout the staging exists to retire. The header is where a reader lands when they open a
   * generated file to change a test, so it has to name the directory the author actually edits.
   */
  @Test
  fun `an overridden authoring dir is what the header names`() {
    val rendered =
      renderShell(
        packageName = "xyz.example.app",
        className = "ExampleLongTest",
        mode = TestHostMode.BaseClass("xyz.block.trailblaze.rules.SquareTrailblazeTest"),
        methods = listOf(recordingDirTrail("ExampleLongTest", "buyHotChocolate")),
        authoringDir = "trails/example",
      )
    assertTrue(
      rendered.contains("// Source: trails/example/ExampleLongTest/ — to change the test"),
      "the header must name the overridden authoring dir, not the module's empty assets dir. " +
        "Got:\n$rendered",
    )
    assertFalse(
      rendered.contains("src/androidTest/assets/trails"),
      "naming src/androidTest/assets/trails here sends an author to a directory with no trails " +
        "in it. Got:\n$rendered",
    )
  }

  /** A trailing slash on the override must not double up in the rendered path. */
  @Test
  fun `an authoring dir with a trailing slash renders one separator`() {
    val rendered =
      renderShell(
        packageName = "xyz.example.app",
        className = "ExampleLongTest",
        mode = TestHostMode.BaseClass("xyz.block.trailblaze.rules.SquareTrailblazeTest"),
        methods = listOf(recordingDirTrail("ExampleLongTest", "buyHotChocolate")),
        authoringDir = "trails/example/",
      )
    assertTrue(
      rendered.contains("// Source: trails/example/ExampleLongTest/ —"),
      "expected exactly one separator before the class dir. Got:\n$rendered",
    )
  }

  /**
   * A lane whose trails are cloned from another repo and flattened into one class has no directory
   * of the `<dir>/<ClassName>/` shape to name. The add/rename/remove guidance names a directory to
   * act in, so emitting it here would send a reader to a path that exists in neither repo. The note
   * has to replace that guidance, not fill it in.
   */
  @Test
  fun `a source note replaces the directory guidance instead of naming a directory`() {
    val rendered =
      renderShell(
        packageName = "xyz.block.trailblaze.uitests.gittrails",
        className = "GitTrailsLongTest",
        mode = TestHostMode.BaseClass("xyz.block.trailblaze.rules.SquareTrailblazeTest"),
        methods = listOf(recordingDirTrail("GitTrailsLongTest", "someClonedTrail")),
        sourceNote = "the GitTrailSource repo this lane clones",
      )
    assertTrue(
      rendered.contains("// Source: the GitTrailSource repo this lane clones"),
      "the header must say where the trails come from. Got:\n$rendered",
    )
    assertFalse(
      rendered.contains("src/androidTest/assets/trails"),
      "a note must suppress the default directory, which backs nothing for this lane. " +
        "Got:\n$rendered",
    )
    assertFalse(
      rendered.contains("recording directories under that directory"),
      "the add/rename/remove guidance names a directory to act in, and this lane has none, so it " +
        "must not be rendered alongside a note. Got:\n$rendered",
    )
  }

  /** With no note, the directory guidance is still what a normal in-place module gets. */
  @Test
  fun `without a source note the directory guidance still renders`() {
    val rendered =
      renderShell(
        packageName = "xyz.example.app",
        className = "ExampleLongTest",
        mode = TestHostMode.BaseClass("xyz.block.trailblaze.rules.SquareTrailblazeTest"),
        methods = listOf(recordingDirTrail("ExampleLongTest", "buyHotChocolate")),
      )
    assertTrue(
      rendered.contains("// Source: src/androidTest/assets/trails/ExampleLongTest/"),
      "the in-place default must survive adding the note property. Got:\n$rendered",
    )
    assertTrue(
      rendered.contains("recording directories under that directory"),
      "the directory guidance must survive adding the note property. Got:\n$rendered",
    )
  }

  @Test
  fun `BaseClass mode renders multiple @Test methods separated by a blank line`() {
    val rendered =
      renderShell(
        packageName = "xyz.block.trailblaze.evaluation",
        className = "SquareCustomToolEvalLongTest",
        mode = TestHostMode.BaseClass("xyz.block.trailblaze.rules.SquareTrailblazeTest"),
        methods =
          listOf(
            namedTrail("SquareCustomToolEvalLongTest", "squareAddItemToCart"),
            namedTrail("SquareCustomToolEvalLongTest", "squareInputTextRandom"),
          ),
      )
    // The shape we want: one blank line between successive @Test fun declarations, and the closing
    // brace on its own line. That matches what a human would have written and lets ktfmt no-op the
    // file (the rendered text is already in the canonical formatting).
    assertEquals(
      listOf(
        "class SquareCustomToolEvalLongTest : SquareTrailblazeTest() {",
        "",
        "  @Test fun squareAddItemToCart() = runFromAsset()",
        "",
        "  @Test fun squareInputTextRandom() = runFromAsset()",
        "}",
        "",
      ),
      rendered.lines().dropWhile { !it.startsWith("class ") },
    )
  }

  // ---- Pattern B: inline-rule mode (OSS default; matches GeneratedSampleAppTests in OSS) ----

  @Test
  fun `InlineRule mode renders shell using AndroidTrailblazeRule with explicit asset paths`() {
    // Short class + method names keep the call on one line (under the ktfmt-preferred ~95 chars).
    // The three-line-wrap branch is covered by a separate test below.
    val rendered =
      renderShell(
        packageName = "xyz.example.app",
        className = "FooLongTest",
        mode = TestHostMode.InlineRule("xyz.block.trailblaze.android.AndroidTrailblazeRule"),
        methods = listOf(namedTrail("FooLongTest", "alpha")),
      )
    val expected =
      """
      // *** DO NOT EDIT — this file is generated by xyz.block.trailblaze.android-gradle. ***
      // Source: src/androidTest/assets/trails/FooLongTest/ — to change the test surface, add /
      // rename / remove the matching <methodName>.trail.yaml files or <methodName>/trail.yaml
      // recording directories under that directory.

      package xyz.example.app

      import org.junit.Rule
      import org.junit.Test
      import xyz.block.trailblaze.android.AndroidTrailblazeRule

      class FooLongTest {

        @get:Rule val rule = AndroidTrailblazeRule()

        @Test fun alpha() = rule.runFromAsset("trails/FooLongTest/alpha.trail.yaml")
      }
      """.trimIndent() + "\n"
    assertEquals(expected, rendered)
  }

  @Test
  fun `InlineRule mode wraps long single-line runFromAsset calls across three lines for ktfmt fit`() {
    // A long class + method name pushes the single-line shape past the ktfmt-preferred ~95 chars.
    // The renderer should fall back to the three-line shape (`@Test` / `fun … () =` / indented
    // call) used by the OSS sample-app generator, so spotless / ktfmt no-ops the emitted file.
    val rendered =
      renderShell(
        packageName = "xyz.example.app",
        className = "VeryLongClassNameForAnAndroidLongTestThatPushesPastNinetyFive",
        mode = TestHostMode.InlineRule("xyz.block.trailblaze.android.AndroidTrailblazeRule"),
        methods =
          listOf(
            namedTrail(
              "VeryLongClassNameForAnAndroidLongTestThatPushesPastNinetyFive",
              "aSimilarlyLongMethodName",
            )
          ),
      )
    assertTrue("expected three-line wrap in: $rendered") {
      rendered.contains("@Test\n") &&
        rendered.contains("fun aSimilarlyLongMethodName() =\n") &&
        rendered.contains(
          "    rule.runFromAsset(\"trails/VeryLongClassNameForAnAndroidLongTestThatPushesPastNinetyFive/aSimilarlyLongMethodName.trail.yaml\")"
        )
    }
  }

  @Test
  fun `rejects an asset directory whose name is not a valid Kotlin simple identifier`() {
    val e =
      assertFailsWith<IllegalArgumentException> {
        GenerateAndroidTrailJUnitShellsTask.validateSimpleName("123StartsWithDigit", source = "(test)")
      }
    assertEquals(
      "Invalid Kotlin identifier `123StartsWithDigit` (from (test)). Class-directory names under " +
        "`src/androidTest/assets/trails/` must be valid Kotlin simple identifiers.",
      e.message,
    )
  }

  @Test
  fun `rejects a methodName whose filename derives to an invalid Kotlin identifier`() {
    val e =
      assertFailsWith<IllegalArgumentException> {
        GenerateAndroidTrailJUnitShellsTask.validateMethodName(
          "with-dash",
          source = "SquareCustomToolEvalLongTest/with-dash.trail.yaml",
        )
      }
    assertEquals(
      "Invalid Kotlin method identifier `with-dash` (from SquareCustomToolEvalLongTest/with-dash.trail.yaml). " +
        "Each <methodName>.trail.yaml filename and <methodName>/ recording-directory name must " +
        "produce a valid Kotlin simple identifier.",
      e.message,
    )
  }

  @Test
  fun `rejects a class-directory whose name is a Kotlin hard keyword`() {
    // `when` matches SIMPLE_NAME_REGEX but is a Kotlin hard keyword — without this check the
    // generator would emit `class when : ...` and Kotlin compile would fail downstream with a
    // confusing error pointing at the generated file instead of the directory.
    val e =
      assertFailsWith<IllegalArgumentException> {
        GenerateAndroidTrailJUnitShellsTask.validateSimpleName("when", source = "(test)")
      }
    assertEquals(
      "Invalid Kotlin identifier `when` (from (test)). `when` is a Kotlin hard keyword and " +
        "cannot be used as a class name. Rename the directory.",
      e.message,
    )
  }

  @Test
  fun `rejects a method whose filename is a Kotlin hard keyword`() {
    val e =
      assertFailsWith<IllegalArgumentException> {
        GenerateAndroidTrailJUnitShellsTask.validateMethodName("fun", source = "FooLongTest/fun.trail.yaml")
      }
    assertEquals(
      "Invalid Kotlin method identifier `fun` (from FooLongTest/fun.trail.yaml). `fun` is a " +
        "Kotlin hard keyword and cannot be used as a method name. Rename the file or directory.",
      e.message,
    )
  }

  @Test
  fun `accepts a name that matches a Kotlin soft keyword (those are valid identifiers)`() {
    // Soft keywords like `by`, `get`, `set`, `field`, `catch` are valid identifiers in Kotlin and
    // intentionally NOT in the hard-keyword reject set. A trail file named `by.trail.yaml` should
    // produce `@Test fun by() = runFromAsset()` without complaint.
    GenerateAndroidTrailJUnitShellsTask.validateMethodName("by", source = "FooLongTest/by.trail.yaml")
    GenerateAndroidTrailJUnitShellsTask.validateMethodName("get", source = "FooLongTest/get.trail.yaml")
    GenerateAndroidTrailJUnitShellsTask.validateMethodName("field", source = "FooLongTest/field.trail.yaml")
  }

  @Test
  fun `rejects a single underscore as a class or method name`() {
    // `_` matches SIMPLE_NAME_REGEX (one underscore = valid identifier per the regex) and is NOT
    // a Kotlin hard keyword, so the existing checks let it through. Kotlin 1.5+ reserves `_` for
    // anonymous bindings (lambda params, destructuring), so a generated class or method named `_`
    // is almost certainly unintended.
    assertFailsWith<IllegalArgumentException> {
      GenerateAndroidTrailJUnitShellsTask.validateSimpleName("_", source = "(test)")
    }.also {
      assertEquals(
        "Invalid Kotlin identifier `_` (from (test)). `_` is reserved in Kotlin for anonymous " +
          "bindings — rename the directory to a meaningful test-class name.",
        it.message,
      )
    }
    assertFailsWith<IllegalArgumentException> {
      GenerateAndroidTrailJUnitShellsTask.validateMethodName("_", source = "FooLongTest/_.trail.yaml")
    }
  }

  @Test
  fun `accepts a valid Kotlin package name`() {
    GenerateAndroidTrailJUnitShellsTask.validatePackageName("xyz.block.trailblaze.evaluation")
    GenerateAndroidTrailJUnitShellsTask.validatePackageName("a")
    GenerateAndroidTrailJUnitShellsTask.validatePackageName("a.b.c")
    // Underscores + mixed case are syntactically legal (style aside).
    GenerateAndroidTrailJUnitShellsTask.validatePackageName("_root.subPkg")
  }

  @Test
  fun `rejects malformed package names that would generate broken Kotlin`() {
    listOf(
      "",
      "123abc", // leading digit
      "a..b", // empty segment between dots
      ".leading",
      "trailing.",
      "has-dash.x", // dash is illegal in Kotlin/Java identifiers
    ).forEach { bad ->
      assertFailsWith<IllegalArgumentException>("expected `$bad` to be rejected") {
        GenerateAndroidTrailJUnitShellsTask.validatePackageName(bad)
      }
    }
  }

  @Test
  fun `rejects a baseClassFqn that historically slipped past the contains-dot check`() {
    // The original validation was a plain `contains('.')` — `"xyz."` passed it, then
    // `substringAfterLast('.')` returned "" and the renderer emitted `class X : () {`, a Kotlin
    // compile error pointing at the generated file. Lock the strengthened FQN regex against these
    // shapes.
    listOf(
      "NoDot",
      "xyz.", // trailing dot — the historical bug
      ".xyz",
      "xyz..Bar",
      "1xyz.Bar", // leading digit in first segment
      "xyz.1Bar",
      "",
    ).forEach { bad ->
      assertFailsWith<IllegalArgumentException>("expected `$bad` to be rejected") {
        GenerateAndroidTrailJUnitShellsTask.validateBaseClassFqn(bad)
      }
    }
  }

  @Test
  fun `accepts a well-formed fully qualified base class name`() {
    GenerateAndroidTrailJUnitShellsTask.validateBaseClassFqn(
      "xyz.block.trailblaze.rules.SquareTrailblazeTest"
    )
    // Two segments is the minimum (one dot required).
    GenerateAndroidTrailJUnitShellsTask.validateBaseClassFqn("a.B")
  }

  @Test
  fun `InlineRule mode passes the DIRECTORY path for a recording-directory trail`() {
    // `<ClassName>/<methodName>/trail.yaml` recordings emit the directory path, not the file —
    // the runtime resolves the best file inside it (classifier-specific recording → trail.yaml →
    // blaze.yaml), same contract hand-written shells that pass a directory path rely on.
    val rendered =
      renderShell(
        packageName = "xyz.example.app",
        className = "FooLongTest",
        mode = TestHostMode.InlineRule("xyz.block.trailblaze.android.AndroidTrailblazeRule"),
        methods = listOf(recordingDirTrail("FooLongTest", "checkout_happy_path")),
      )
    assertTrue("expected a directory asset path in: $rendered") {
      rendered.contains(
        "@Test fun checkout_happy_path() = rule.runFromAsset(\"trails/FooLongTest/checkout_happy_path\")"
      )
    }
  }

  @Test
  fun `BaseClass mode emits the same no-arg runFromAsset for a recording-directory trail`() {
    // The stack-trace resolver probes the directory-per-test shape itself, so the emit is
    // identical to a named trail's.
    val rendered =
      renderShell(
        packageName = "xyz.example.app",
        className = "FooLongTest",
        mode = TestHostMode.BaseClass("xyz.block.trailblaze.rules.SquareTrailblazeTest"),
        methods = listOf(recordingDirTrail("FooLongTest", "checkout_happy_path")),
      )
    assertTrue("expected a no-arg runFromAsset in: $rendered") {
      rendered.contains("@Test fun checkout_happy_path() = runFromAsset()")
    }
  }
}
