package xyz.block.trailblaze.toolcalls

import java.io.File
import kotlin.reflect.KClass
import kotlin.reflect.full.findAnnotation
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import xyz.block.trailblaze.config.InlineScriptToolConfig
import xyz.block.trailblaze.config.ToolYamlConfig
import xyz.block.trailblaze.config.toTrailblazeToolDescriptor
import xyz.block.trailblaze.util.Console

/**
 * Renders one tool's Markdown detail page. The same renderer powers three callers so that
 * every per-tool doc surface in the project (workspace `trailblaze check` sidecars, the
 * framework reference docs under `docs/generated/functions/custom/`, and
 * the internal per-target docs under `docs/internal/targets/<id>/tools/`) shares one
 * source of truth for what a tool's documentation looks like — if a field is missing,
 * every caller surfaces the same gap.
 *
 * Three input shapes are handled:
 *
 *  - [ClassBacked] — Kotlin-backed [TrailblazeTool] class. Description + parameter list come
 *    from the class's `@TrailblazeToolClass` + `@LLMDescription` + constructor reflection.
 *  - [YamlDefined] — `tools:`-mode YAML composition. Description + parameter list come from
 *    the YAML file ([ToolYamlConfig]).
 *  - [Scripted] — author-owned JS/TS module registered as an MCP tool. Description + input
 *    schema come from the [InlineScriptToolConfig] (which mirrors the per-trailmap
 *    `<trailmap>/tools/<id>.yaml` shape after schema translation).
 *
 * The renderer never fabricates metadata. Missing descriptions render as
 * `_(no description provided)_` and absent parameter sections are omitted cleanly.
 *
 * Output schema is intentionally rendered as the current opaque-text-content shape — typed
 * result schemas (the in-flight `kind: query | action`, MCP `structuredContent`, etc.) are
 * deliberately out of scope here. When the manifest layer gains a typed result, plumb it
 * through [ToolDetail] and update the renderer; no other call sites need to change.
 */
object ResolvedTargetToolDetailRenderer {

  /**
   * Stable orphan-cleanup marker emitted as the **first line** of every per-tool sidecar
   * file the project writes — workspace `trailblaze check`, OSS `:docs:generator:run`, and
   * internal `:internal-docs-generator:run` all share this exact string. Orphan-prune
   * passes in each caller (`ResolvedTargetReportEmitter.deleteOrphanSidecarFiles`,
   * `DocsGenerator.generate`, `TargetToolBaselineGenerator.pruneStaleSidecars`) recognize
   * emitter-owned files by this prefix and only delete files that carry it; hand-authored
   * markdown in the same directory survives untouched.
   *
   * **Why the literal still mentions "trailblaze check"** — even though the OSS and
   * internal gradle generators also produce these files, this constant is a *marker*
   * read by string-equality by every cleanup path, including files committed to disk
   * across multiple repos. Renaming it would strand pre-existing committed sidecars as
   * "not emitter-owned" and either skip the orphan-prune step (stale files linger) or
   * require coordinated migration tooling. The marker is intentionally a stable lie.
   *
   * User-facing "how do I regenerate this file?" guidance lives on the **second header
   * line** (the caller-supplied [Header.regenerateHint]) — that's the source of truth a
   * reader should follow when they want to refresh a sidecar.
   */
  const val GENERATED_BANNER: String = "<!-- GENERATED BY trailblaze check. DO NOT EDIT. -->"

  /** Per-tool metadata fed to [renderMarkdown]. */
  sealed class ToolDetail {
    abstract val name: String

    data class ClassBacked(
      override val name: String,
      val kclass: KClass<out TrailblazeTool>,
    ) : ToolDetail()

    data class YamlDefined(
      override val name: String,
      val config: ToolYamlConfig,
    ) : ToolDetail()

    data class Scripted(
      override val name: String,
      val config: InlineScriptToolConfig,
      val originTrailmapId: String,
      val consumerTrailmapId: String,
      /**
       * Trailmap root on disk when the origin trailmap is filesystem-backed. Used to render
       * `script:` paths relative to the trailmap root (`./tools/foo.ts`) rather than as the
       * resolved absolute path the runtime carries — that absolute path is per-machine and
       * makes the committed sidecar churn whenever the workspace moves. Null for classpath-
       * backed trailmaps (rendered as the raw `script` field, which the loader leaves alone).
       */
      val originTrailmapDir: File? = null,
    ) : ToolDetail()
  }

  /**
   * Header banner emitted at the top of every per-tool Markdown file. The first line is the
   * stable [GENERATED_BANNER] every orphan-cleanup pass recognizes; the surrounding comment
   * lines are caller-supplied (which workspace/target/generator owns this file, and how to
   * regenerate it) so downstream pipelines can preserve their authoring story without
   * forking the renderer.
   */
  data class Header(
    /** Short identifier the caller wants displayed (e.g. `wikipedia`, `framework catalog`). */
    val origin: String,
    /** Plain-English regen instruction, shown verbatim in a header comment. */
    val regenerateHint: String,
  )

  /**
   * Renders [detail] as a complete sidecar Markdown document. The leading [GENERATED_BANNER]
   * and the "Regenerate with: trailblaze check" hint are emitted by this function so callers
   * never have to prepend boilerplate. This is the entry point the workspace
   * [ResolvedTargetReportEmitter] uses.
   */
  fun renderMarkdown(detail: ToolDetail, targetId: String): String =
    renderMarkdown(
      detail = detail,
      header = Header(
        origin = "Sidecar for target: $targetId",
        regenerateHint = "Regenerate with: trailblaze check",
      ),
    )

  /**
   * Caller-configurable variant — same content as [renderMarkdown] but with the second/third
   * preamble lines under caller control. Used by `:docs:generator:run` and
   * `:internal-docs-generator:run` so they can label files with their own regen instruction
   * while still sharing the per-tool rendering logic.
   */
  fun renderMarkdown(detail: ToolDetail, header: Header): String = buildString {
    appendLine(GENERATED_BANNER)
    appendLine("<!-- ${header.origin} -->")
    appendLine("<!-- ${header.regenerateHint} -->")
    appendLine()
    appendLine("# `${detail.name}`")
    appendLine()
    when (detail) {
      is ToolDetail.ClassBacked -> renderClassBacked(detail)
      is ToolDetail.YamlDefined -> renderYamlDefined(detail)
      is ToolDetail.Scripted -> renderScripted(detail)
    }
    appendLine("## Output")
    appendLine()
    appendLine("Returns: `string` (opaque text content)")
    appendLine()
    appendLine(
      "Typed result schemas (`kind: query | action`, MCP `structuredContent`) are not yet " +
        "carried by the resolved manifest — this section will gain detail when that lands.",
    )
    appendLine()
  }

  private fun StringBuilder.renderClassBacked(detail: ToolDetail.ClassBacked) {
    val descriptor = runCatching { detail.kclass.buildToolDescriptorIgnoringSurface() }
      .onFailure { e ->
        // Surface descriptor-build failures so a misannotated tool class (missing
        // `@LLMDescription`, unsupported parameter shape, etc.) is observable in logs
        // rather than silently rendering as "parameter list not available." The sidecar
        // still emits — degrading metadata, not the whole emission.
        Console.error(
          "ResolvedTargetToolDetailRenderer: failed to build descriptor for class-backed " +
            "tool `${detail.name}` (${detail.kclass.qualifiedName ?: detail.kclass.simpleName}): " +
            "${e::class.simpleName}: ${e.message}",
        )
      }
      .getOrNull()
    val description = descriptor?.description?.takeIf { it.isNotBlank() }
    appendLine(description ?: "_(no description provided)_")
    appendLine()
    appendLine("## Source")
    appendLine()
    appendLine("- Kind: class-backed")
    val fqn = detail.kclass.qualifiedName ?: detail.kclass.simpleName ?: "<anonymous>"
    appendLine("- Class: `$fqn`")
    appendLine()
    val annotation = detail.kclass.findAnnotation<TrailblazeToolClass>()
    if (annotation != null) {
      renderClassBackedContract(
        surfaceToLlm = annotation.surfaceToLlm,
        isRecordable = annotation.isRecordable,
        requiresHost = annotation.requiresHost,
      )
    }
    if (descriptor == null) {
      appendLine("## Input schema")
      appendLine()
      appendLine("_(descriptor build failed — parameter list not available)_")
      appendLine()
      return
    }
    renderKoogParams(
      required = descriptor.requiredParameters.map {
        ParamRow(it.name, it.type.toString(), it.description.takeIf(String::isNotBlank))
      },
      optional = descriptor.optionalParameters.map {
        ParamRow(it.name, it.type.toString(), it.description.takeIf(String::isNotBlank))
      },
    )
  }

  private fun StringBuilder.renderYamlDefined(detail: ToolDetail.YamlDefined) {
    val descriptor = runCatching { detail.config.toTrailblazeToolDescriptor() }
      .onFailure { e ->
        // Log so a malformed yaml-defined tool descriptor (wrong mode, missing fields, etc.)
        // is observable rather than silently rendering as a stripped-down sidecar.
        Console.error(
          "ResolvedTargetToolDetailRenderer: failed to build descriptor for YAML-defined " +
            "tool `${detail.name}` (id=${detail.config.id}): " +
            "${e::class.simpleName}: ${e.message}",
        )
      }
      .getOrNull()
    val description = descriptor?.description ?: detail.config.description?.takeIf { it.isNotBlank() }
    appendLine(description ?: "_(no description provided)_")
    appendLine()
    appendLine("## Source")
    appendLine()
    appendLine("- Kind: YAML-defined")
    appendLine("- Tool id: `${detail.config.id}`")
    appendLine()
    renderClassBackedContract(
      surfaceToLlm = detail.config.surfaceToLlm ?: true,
      isRecordable = detail.config.isRecordable ?: true,
      requiresHost = detail.config.requiresHost ?: false,
    )
    if (descriptor != null) {
      renderKoogParams(
        required = descriptor.requiredParameters.toRows(),
        optional = descriptor.optionalParameters.toRows(),
      )
      return
    }
    // Fall back to the raw `parameters:` block on the YAML config — toTrailblazeToolDescriptor
    // throws if the YAML is in `class:` mode (shouldn't happen here, but guard anyway).
    val (required, optional) = detail.config.parameters.partition { it.required }
    renderKoogParams(
      required = required.map { ParamRow(it.name, it.type, it.description?.takeIf(String::isNotBlank)) },
      optional = optional.map { ParamRow(it.name, it.type, it.description?.takeIf(String::isNotBlank)) },
    )
  }

  private fun StringBuilder.renderScripted(detail: ToolDetail.Scripted) {
    val description = detail.config.description?.takeIf { it.isNotBlank() }
    appendLine(description ?: "_(no description provided)_")
    appendLine()
    appendLine("## Source")
    appendLine()
    appendLine("- Kind: scripted")
    val scriptDisplay = renderScriptPath(detail.config.script, detail.originTrailmapDir)
    appendLine("- Script: `$scriptDisplay`")
    if (detail.originTrailmapId == detail.consumerTrailmapId) {
      appendLine("- Origin trailmap: `${detail.originTrailmapId}` (declared by this trailmap)")
    } else {
      appendLine(
        "- Origin trailmap: `${detail.originTrailmapId}` (exported via `exports:` and consumed by " +
          "`${detail.consumerTrailmapId}`)",
      )
    }
    detail.config.runtime?.let { appendLine("- Runtime: `$it` (explicit override)") }
    appendLine()
    renderScriptedContract(requiresHost = detail.config.requiresHost)
    renderScriptedInputSchema(detail.config.inputSchema)
  }

  private fun StringBuilder.renderScriptedInputSchema(schema: JsonObject) {
    if (schema.isEmpty()) {
      appendLine("## Input schema")
      appendLine()
      appendLine("_(no input schema provided)_")
      appendLine()
      return
    }
    val properties = (schema["properties"] as? JsonObject).orEmpty()
    val required = (schema["required"] as? JsonArray).orEmpty().mapNotNull {
      (it as? JsonPrimitive)?.contentOrNull()
    }.toSet()
    if (properties.isEmpty()) {
      appendLine("## Input schema")
      appendLine()
      appendLine("_(input schema declares no properties)_")
      appendLine()
      return
    }
    val rows = properties.entries
      .sortedBy { it.key }
      .map { (paramName, paramSchema) ->
        val (type, description) = schemaTypeAndDescription(paramSchema)
        ParamRow(name = paramName, type = type, description = description)
      }
    val requiredRows = rows.filter { it.name in required }
    val optionalRows = rows.filter { it.name !in required }
    renderKoogParams(required = requiredRows, optional = optionalRows)
  }

  private fun schemaTypeAndDescription(node: JsonElement): Pair<String, String?> {
    val obj = (node as? JsonObject) ?: return "object" to null
    val rawType = (obj["type"] as? JsonPrimitive)?.contentOrNull()
    val items = (obj["items"] as? JsonObject)
    val enumValues = (obj["enum"] as? JsonArray)?.mapNotNull { (it as? JsonPrimitive)?.contentOrNull() }
    val type = when {
      rawType == "array" && items != null -> {
        val (inner, _) = schemaTypeAndDescription(items)
        "array<$inner>"
      }
      !enumValues.isNullOrEmpty() -> "enum(${enumValues.joinToString(" | ")})"
      rawType != null -> rawType
      else -> "any"
    }
    val description = (obj["description"] as? JsonPrimitive)?.contentOrNull()?.takeIf { it.isNotBlank() }
    return type to description
  }

  private fun JsonPrimitive.contentOrNull(): String = content

  /**
   * Renders the `## Contract` block for class-backed and YAML-defined tools. All three flags
   * are sourced authoritatively (annotation reflection for class-backed; `ToolYamlConfig`
   * fields with `null`-default fallback for YAML-defined) and always emitted, so a reader
   * scanning a sidecar can answer "is this LLM-visible / recordable / host-only?" without
   * having to grep Kotlin source or the runtime registry. The literal `surface_to_llm` /
   * `is_recordable` / `requires_host` tokens mirror the YAML schema keys so a YAML author
   * sees the exact field name they would set.
   *
   * Catches the bug class that motivated this section — PR #3407 added `isRecordable = false`
   * to `AndroidSendBroadcastTrailblazeTool` after a sibling tool's kdoc claimed it was
   * non-recordable but the annotation hadn't actually set the flag. Surfacing the flag in
   * the per-tool sidecar makes those mismatches diff-reviewable.
   */
  private fun StringBuilder.renderClassBackedContract(
    surfaceToLlm: Boolean,
    isRecordable: Boolean,
    requiresHost: Boolean,
  ) {
    appendLine("## Contract")
    appendLine()
    appendLine("- Visible to LLM: ${yesNo(surfaceToLlm)} (`surface_to_llm: $surfaceToLlm`)")
    appendLine("- Recordable: ${yesNo(isRecordable)} (`is_recordable: $isRecordable`)")
    appendLine("- Host-only: ${yesNo(requiresHost)} (`requires_host: $requiresHost`)")
    appendLine()
  }

  /**
   * Scripted-tool variant of [renderClassBackedContract]. Only `requires_host` carries
   * authored intent for scripted tools — `surfaceToLlm` and `isRecordable` aren't fields on
   * [InlineScriptToolConfig] and the runtime treats scripted tools as always LLM-visible and
   * always recordable. Rendering the irrelevant flags would imply they're tunable per-tool,
   * which they aren't at this layer.
   */
  private fun StringBuilder.renderScriptedContract(requiresHost: Boolean) {
    appendLine("## Contract")
    appendLine()
    appendLine("- Host-only: ${yesNo(requiresHost)} (`requires_host: $requiresHost`)")
    appendLine()
  }

  private fun yesNo(value: Boolean): String = if (value) "yes" else "no"

  private fun StringBuilder.renderKoogParams(required: List<ParamRow>, optional: List<ParamRow>) {
    if (required.isEmpty() && optional.isEmpty()) {
      appendLine("## Input schema")
      appendLine()
      appendLine("_(no parameters)_")
      appendLine()
      return
    }
    appendLine("## Input schema")
    appendLine()
    if (required.isNotEmpty()) {
      appendLine("### Required parameters")
      appendLine()
      required.forEach { row -> appendParamRow(row) }
      appendLine()
    }
    if (optional.isNotEmpty()) {
      appendLine("### Optional parameters")
      appendLine()
      optional.forEach { row -> appendParamRow(row) }
      appendLine()
    }
  }

  private fun StringBuilder.appendParamRow(row: ParamRow) {
    appendLine("- `${row.name}` — `${row.type}`")
    if (!row.description.isNullOrBlank()) {
      appendLine("  ${row.description.trim()}")
    }
  }

  private data class ParamRow(val name: String, val type: String, val description: String?)

  private fun List<TrailblazeToolParameterDescriptor>.toRows(): List<ParamRow> = map { p ->
    ParamRow(name = p.name, type = p.type, description = p.description?.takeIf(String::isNotBlank))
  }

  /**
   * Pretty-prints a scripted-tool script path. Trailmap loaders resolve the authored
   * `./tools/foo.ts` into the absolute filesystem path before stamping it onto
   * [InlineScriptToolConfig.script], which makes the sidecar leak per-machine absolute paths
   * and churn whenever the workspace moves. When we know the origin trailmap dir, render the
   * path relative to it; otherwise fall back to the raw value the runtime carries.
   */
  private fun renderScriptPath(rawScript: String, originTrailmapDir: File?): String {
    if (originTrailmapDir == null) return rawScript
    val asFile = runCatching { File(rawScript) }.getOrNull() ?: return rawScript
    if (!asFile.isAbsolute) return rawScript
    val trailmapBase = runCatching { originTrailmapDir.canonicalFile }.getOrNull() ?: return rawScript
    val scriptBase = runCatching { asFile.canonicalFile }.getOrNull() ?: return rawScript
    val trailmapPath = trailmapBase.toPath()
    val scriptPath = scriptBase.toPath()
    if (!scriptPath.startsWith(trailmapPath)) return rawScript
    val relative = trailmapPath.relativize(scriptPath).toString().replace('\\', '/')
    return "./$relative"
  }

  private fun JsonObject?.orEmpty(): JsonObject = this ?: JsonObject(emptyMap())
  private fun JsonArray?.orEmpty(): JsonArray = this ?: JsonArray(emptyList())
}
