// Vendored bindings for the small RESIDUAL set of Trailblaze framework tools that the generated
// recordable-tool surface can't own. Augments [TrailblazeToolMap] so authors get autocomplete +
// type-checking the moment they import from `@trailblaze/scripting`. No `npm install` on the
// consumer side; the SDK ships these.
//
// ## Split with the generated recordable surface
//
// Every RECORDABLE framework tool (class-backed + YAML-defined) is generated into each trailmap's /
// bundled target's `tools/trailblaze-client.d.ts` by `PerTrailmapClientDtsEmitter`, derived from the
// `@TrailblazeToolClass(isRecordable = true)` source of truth (see the devlog
// `2026-07-01-trail-recording-type-validation.md`). That generated surface is what the trail-recording
// type-validator checks against — sourcing it from `isRecordable` means it can't drift or silently
// miss a recordable tool (the failure mode this file used to have: a hand-added `tapOn` /
// `assertVisibleBySelector` while `assertNotVisibleBySelector` was forgotten).
//
// This hand file keeps ONLY the tools the generator deliberately does NOT emit, so the two never
// declare the same `TrailblazeToolMap` key (a duplicate key with a different shape is a TS2717 error
// that would break the whole validation compilation):
//
//  - **Non-recordable author utilities** (`isRecordable = false`, never in a recording): the
//    selector query tools `findMatches` / `waitUntilNotVisible` (rich `MatchDescriptor[]` / `boolean`
//    results), plus the host/composition primitives `exec`, `android_writeBytesToFile`,
//    `android_adbShell`, `android_sendBroadcast`, `android_writeFileToDownloads`.
//  - **Recordable tools the generator can't fully model** — `mobile_maestro` (free-form Maestro
//    commands the descriptor lowering can't express) and `mobile_listInstalledApps` /
//    `mobile_listInstalledAppsDetailed` (structured result types). These are listed in
//    `HandCuratedRecordableTools.NAMES` so the generator skips them;
//    `BuiltInToolsBindingDriftTest` asserts the two sets stay disjoint.
//
// Result types: `result` is `string` unless the tool declares `@TrailblazeToolClass(resultType = ...)`
// and populates `structuredContent`. `mobile_listInstalledApps[Detailed]` do — their result types
// here are *generated* (imported below from `built-in-tool-results.js`, emitted by
// `BuiltInToolResultTsBindings` in `trailblaze-common`), not hand-written, so this file and any
// generated surface render the identical type from that one annotation.
//
// Pulled in by `index.ts` via a bare side-effect import. The file has no runtime exports — only
// declaration-merging augmentations on the `@trailblaze/scripting` module — but it IS a module (the
// `export {}` below) so TypeScript treats the `declare module` block as augmentation rather than
// re-declaration.
//
// When adding/removing an entry here or changing its arg shape, mirror the Kotlin change (the
// `@Serializable` tool class is the runtime contract these TS types shadow). Each entry links its
// source-of-truth Kotlin file.

// Selector-grammar types — `TrailblazeNodeSelector` and `MatchDescriptor` — are generated from the
// Kotlin sealed-class hierarchy by `:trailblaze-models:generateSelectorsTs` and re-exported from
// `index.ts`. The `findMatches` / `waitUntilNotVisible` entries below reference them; this file
// imports the type names locally for the declaration-merging block.
import type {
  MatchDescriptor,
  TrailblazeNodeSelector,
} from "./generated/selectors.js";
// Generated from each tool's declared `resultType` by `BuiltInToolResultTsBindings`
// (`:trailblaze-common:generateDtoTs`) — see `ListInstalledAppsTrailblazeTool.kt`.
import type {
  InstalledApp,
  ListInstalledAppsDetailedResult,
  ListInstalledAppsResult,
} from "./generated/built-in-tool-results.js";

// Pins the imported shapes so `tsc` catches drift. Needed because `bun:test` never type-checks
// and `*.test.ts` is excluded from this SDK's tsconfig, so a test-file import wouldn't catch it.
const _installedAppShape: InstalledApp = { appId: "com.example.app", isSystemApp: false };
const _listResultShape: ListInstalledAppsResult = { appIds: [_installedAppShape.appId] };
const _detailedResultShape: ListInstalledAppsDetailedResult = { apps: [_installedAppShape] };

declare module "@trailblaze/scripting" {
  interface TrailblazeToolMap {
    // MAINTAINER NOTE (contract): the Kotlin Koog/scripted-tool descriptor — generated by
    // `TrailblazeKoogToolExt` — intentionally OMITS the selector types (`TrailblazeNodeSelector`
    // and the legacy `TrailblazeElementSelector`, via its `excludedParameterTypes`) because
    // reflecting their self-referencing fields (childOf / containsChild / …) overflows the stack
    // during descriptor codegen. For RECORDABLE selector tools the generated recordable surface
    // re-injects the selector arg via `selectorParamsForTs` — but `findMatches` / `waitUntilNotVisible`
    // are `isRecordable = false` (never in a recording), so they aren't in the generated surface and
    // THIS hand-curated `selector` / `nodeSelector` typing is their authoritative scripted-author
    // surface. Keep it in sync with the Kotlin tool classes by hand.
    /**
     * Resolve a [TrailblazeNodeSelector] against the current view hierarchy and return
     * every match as a [MatchDescriptor] list. Read-only — never mutates the device.
     *
     * Use the result length as a visibility / uniqueness gate:
     *
     * ```ts
     * const matches = await client.tools.findMatches({
     *   selector: { androidAccessibility: { textRegex: "Submit" } },
     * });
     * // matches.length === 0  -> not visible
     * // matches.length === 1  -> unique match, safe to act on
     * // matches.length > 1    -> ambiguous, narrow the selector
     * ```
     *
     * Each match carries enough identity + position info (indexPath, bounds, text,
     * accessibilityId, resourceId) to act on without re-querying.
     *
     * Snapshot reuse: calling `findMatches` multiple times within one tool invocation
     * shares the captured view hierarchy via the host-side snapshot cache — the
     * multi-second hierarchy fetch is paid at most once per invocation. An action
     * tool dispatched in the same batch (tap, swipe, inputText, …) invalidates the
     * cache so a follow-up `findMatches` reads the post-action tree.
     *
     * Source: `FindMatchesTrailblazeTool.kt`.
     */
    findMatches: {
      args: {
        /** Selector to match against the current view hierarchy. */
        selector: TrailblazeNodeSelector;
        /**
         * Optional wait budget in milliseconds. Omit (the default) for a single point-in-time
         * snapshot. When set, the tool polls the LIVE hierarchy until at least one match appears
         * or the budget elapses, then returns whatever matched (an empty array if nothing did).
         * This is the non-throwing "wait until this selector is visible" probe for conditional
         * flows — use the result length as the gate (`matches.length === 0` → not visible within
         * the timeout). Prefer this over hand-rolling a poll loop on top of point-in-time calls.
         */
        timeoutMs?: number;
      };
      result: MatchDescriptor[];
    };

    /**
     * Wait (up to `timeoutMs`) for the element matching [nodeSelector] to become NOT visible,
     * returning a NON-THROWING boolean verdict: `true` when the selector is (or became) not
     * visible within the budget, `false` when it is still visible after the wait.
     *
     * The disappearance counterpart to `findMatches` (which waits for APPEARANCE). Use it for
     * conditional flows that must branch on a screen having gone away — and keep their own custom
     * error messages — rather than throwing like the verification-style `assertNotVisibleWithText`:
     *
     * ```ts
     * const gone = await client.tools.waitUntilNotVisible({
     *   nodeSelector: { androidAccessibility: { textRegex: "Loading" } },
     *   timeoutMs: 60_000,
     * });
     * if (!gone) throw new Error("…still loading after 60s; OAuth pipeline stuck.");
     * ```
     *
     * Distinct from negating `findMatches`: a positive probe returns true the moment the text is
     * *currently* on screen, so negating it doesn't wait for the element to actually disappear.
     * This tool waits for the live tree to lose the match. Routes through the driver-native
     * not-visible wait on the accessibility driver, Maestro `extendedWaitUntil` otherwise.
     *
     * Source: `WaitUntilNotVisibleTrailblazeTool.kt` (`waitUntilNotVisible`).
     */
    waitUntilNotVisible: {
      args: {
        /** Selector whose disappearance is awaited against the live view hierarchy. */
        nodeSelector: TrailblazeNodeSelector;
        /**
         * Optional wait budget in milliseconds for the element to disappear. Omit to let each
         * driver apply its own idle/wait policy (per-driver default).
         */
        timeoutMs?: number;
      };
      result: boolean;
    };

    /**
     * Execute raw Maestro commands directly — the escape hatch the Kotlin agent reaches via
     * `runMaestroCommands(...)`. Each entry in `commands` is one Maestro command map in the
     * documented YAML/JSON flow shape (e.g. `{ tapOn: { text: "Verify" } }`,
     * `{ inputText: "123456" }`, `{ extendedWaitUntil: { notVisible: "Loading", timeout: 45000 } }`,
     * `{ assertVisible: { text: "0%", optional: true } }`). Prefer the specific typed tools when one
     * exists; this is for faithful 1:1 ports of Kotlin steps that built Maestro orchestra commands by
     * hand (e.g. app launch / sign-in flows).
     *
     * Recordable, but hand-curated here (listed in `HandCuratedRecordableTools.NAMES`):
     * the free-form `commands` list can't be lowered by the Koog descriptor path, so the generated
     * recordable surface can't model it.
     *
     * Source: `MaestroTrailblazeTool.kt` (`mobile_maestro`). The Kotlin tool's custom serializer maps
     * the `{ commands: [...] }` payload onto a Maestro commands-list YAML before execution.
     *
     * Mobile-only escape hatch: web is Playwright-native (`web_*`), so this is gated to
     * android + ios. Author-only (`surfaceToLlm: false`) — the LLM uses the semantic tools.
     */
    mobile_maestro: {
      args: {
        /** Ordered list of Maestro command maps to run, in `MaestroYamlParser` flow shape. */
        commands: Array<Record<string, unknown>>;
      };
      result: string;
    };

    /**
     * Run a process on the **host** JVM via argv (no shell). Host-only (`requiresHost = true`) — for
     * **tool authors**, not the LLM (`surfaceToLlm = false`). The escape hatch for composing host
     * CLIs from a scripted tool: iOS `xcrun simctl …` (pair with `ctx.device.instanceId` for the
     * simulator UDID), `adb` host subcommands, build steps, etc.
     *
     * Each `argv` element is passed verbatim to `ProcessBuilder` — no shell metacharacter
     * interpretation, so an interpolated value can't be re-read as `;`/`&&`/quotes. Opt into a shell
     * explicitly with `argv: ["sh","-c","<cmd>"]`. Returns combined stdout/stderr; a non-zero exit
     * (≠ `expectedExitCode`) surfaces as an error.
     *
     * Source: `ExecTrailblazeTool.kt` (`exec`).
     */
    exec: {
      args: {
        /** Process argv. Element 0 is the executable; the rest are literal arguments (no shell parsing). */
        argv: string[];
        /** Working directory for the subprocess. Defaults to the daemon's current working directory. */
        workingDir?: string;
        /** Exit code treated as success. Default 0. */
        expectedExitCode?: number;
        /** Optional per-line regex; only matching lines are kept in the success output (ignored on failure). */
        outputFilterRegex?: string;
        /** Wall-clock timeout in seconds before the subprocess is killed. Default: wait indefinitely. */
        timeoutSeconds?: number;
      };
      result: string;
    };

    /**
     * Low-level framework primitive: write raw bytes (supplied as a base64 string) to an absolute
     * path on the Android device, creating parent dirs and overwriting any existing file. Use it
     * to seed any file — text or binary — that the device shell can't move reliably (a file body
     * hangs `adb shell` on the host, and a base64 argv hits ARG_MAX on-device; this uses
     * `adb push` / a direct file write instead).
     *
     * Filesystem only: it does NOT register MediaStore or set a MIME type (base64 carries no MIME,
     * and the filesystem has no MIME concept). To write UTF-8 text, base64-encode the string and
     * pass it here. If a consumer must find the file via a MediaStore query, register it separately
     * with `android_adbShell` (`cmd media_scanner scan <path>` / `content insert --bind mime_type:…`).
     * That layering — and keeping perms/owner/MIME on `adbShell` rather than as params here — is the
     * framework-provides-primitives decision (devlog 2026-06-22). Android-only.
     *
     * Source: `AndroidWriteBytesToFileTrailblazeTool.kt` (`android_writeBytesToFile`).
     */
    android_writeBytesToFile: {
      args: {
        /** Absolute destination path (must start with `/`), e.g. `/storage/emulated/0/Download/setup.json`. */
        devicePath: string;
        /** File content as a base64-encoded byte string; decoded to raw bytes before writing. */
        base64Content: string;
      };
      result: string;
    };

    /**
     * Run an `adb shell` command, argv-shaped (injection-safe). Returns the command's stdout on a
     * zero exit; throws on a non-zero exit or I/O failure. Composition primitive for Android device
     * control from scripted tools. Android-only.
     *
     * Source: `AdbShellTrailblazeTool.kt` (`android_adbShell`).
     */
    android_adbShell: {
      args: {
        /** Argv-shaped command, e.g. `["am", "force-stop", "com.example"]` (NOT one shell string). */
        command: string[];
        /** Optional debuggable-app id to run the command under via `run-as`. */
        runAs?: string;
      };
      result: string;
    };

    /**
     * Send a broadcast intent to the connected Android device. `action` and each extra `value`
     * support `{{token}}` / `${token}` references, resolved host-side against the full agent memory
     * at execution time — so a credential can be forwarded as an opaque token without the plaintext
     * ever entering the JS heap. Non-LLM, non-recordable composition primitive. Android-only.
     *
     * Source: `AndroidSendBroadcastTrailblazeTool.kt` (`android_sendBroadcast`).
     */
    android_sendBroadcast: {
      args: {
        /** Intent action, e.g. `com.example.SIGNIN`. */
        action: string;
        /** Target component package (usually the app id). */
        componentPackage: string;
        /** Target component (receiver) class. */
        componentClass: string;
        /** Intent extras. `value` is the literal `am broadcast` text; `type` defaults to `string`. */
        extras?: Array<{ key: string; value: string; type?: string }>;
      };
      result: string;
    };

    /**
     * Write a UTF-8 text file into the device's public Downloads directory. On-device this writes via
     * `MediaStore.Downloads` (so a consuming app's MediaStore query finds it under scoped storage);
     * from the host it `adb push`es to `/storage/emulated/0/Download`. For an arbitrary raw path with
     * no MediaStore registration, use `android_writeBytesToFile`. Android-only.
     *
     * Source: `AndroidWriteFileToDownloadsTrailblazeTool.kt` (`android_writeFileToDownloads`).
     */
    android_writeFileToDownloads: {
      args: {
        /** File name to create in Downloads, e.g. `setup.json`. */
        fileName: string;
        /** UTF-8 text content. */
        content: string;
      };
      result: string;
    };

    /**
     * Write an image into the device's public Pictures directory and register it as a MediaStore
     * Images row, so a gallery / photo picker finds it. On-device this does a `MediaStore.Images`
     * `ContentResolver.insert` (scoped-storage-safe, auto-registered); from the host it `adb push`es
     * to `/sdcard/Pictures` then triggers a MediaStore `scan_file`. Bytes are passed base64-encoded.
     * Unlike `android_writeBytesToFile` (filesystem only), this produces an Images row in either
     * execution mode. Android-only.
     *
     * Source: `AndroidWriteImageToMediaStoreTrailblazeTool.kt` (`android_writeImageToMediaStore`).
     */
    android_writeImageToMediaStore: {
      args: {
        /** File name to create under Pictures, e.g. `photo.png`. */
        fileName: string;
        /** Image content as a base64-encoded byte string; decoded to raw bytes before writing. */
        base64Content: string;
        /** Image MIME type. Defaults to `image/png`. */
        mimeType?: string;
      };
      result: string;
    };

    /**
     * List the app ids installed on the device. Works on Android (`pm list packages`) and iOS
     * (`xcrun simctl listapps`). Returns the typed result directly (`{ appIds: string[] }`, sorted) —
     * no `JSON.parse` needed. The Kotlin handler populates `structuredContent` with this shape; the
     * SDK proxy unwraps it automatically.
     *
     * Recordable, but hand-curated here (listed in `HandCuratedRecordableTools.NAMES`)
     * so the structured `{ appIds }` result type is preserved — the generated recordable surface would
     * flatten it to `result: string`.
     *
     * The lean, common-case utility. For each app's metadata (display name, system/user, version,
     * build number, install path) use `mobile_listInstalledAppsDetailed` instead.
     *
     * Source: `ListInstalledAppsTrailblazeTool.kt` (`mobile_listInstalledApps`).
     */
    mobile_listInstalledApps: {
      args: Record<string, never>;
      result: ListInstalledAppsResult;
    };

    /**
     * The deep counterpart to `mobile_listInstalledApps`: lists installed apps with full per-app
     * metadata. Returns the typed result directly (sorted by `appId`) — no `JSON.parse` needed. The
     * Kotlin handler populates `structuredContent` with this shape; the SDK proxy unwraps it
     * automatically.
     *
     * Recordable, but hand-curated here (see `mobile_listInstalledApps`) to preserve the structured
     * result type.
     *
     * Pass `{ includeSystemApps: false }` to return only user-installed apps (drops OS apps). On the
     * Android host/adb path only `label` is absent (it needs on-device resource resolution);
     * `isSystemApp` / `version` / `buildNumber` / `installPath` are populated there too via a single
     * `dumpsys package packages` read, and `label` is populated on the Android on-device driver and on iOS.
     *
     * Not surfaced to the LLM — reachable from scripted tools via `callTool`. Use
     * `mobile_listInstalledApps` when you only need ids.
     *
     * Source: `ListInstalledAppsDetailedTrailblazeTool.kt` (`mobile_listInstalledAppsDetailed`).
     */
    mobile_listInstalledAppsDetailed: {
      args: { includeSystemApps?: boolean };
      result: ListInstalledAppsDetailedResult;
    };
  }
}

// Marks this file as a module (rather than a global script) so the `declare module`
// block above is treated as an augmentation of `@trailblaze/scripting` instead of a
// redeclaration that overrides the package's actual exports.
export {};
