// GENERATED BY TRAILBLAZE DAEMON. DO NOT EDIT.
// Re-runs on daemon restart. Idempotent — content-stable across restarts of the same toolset.
// Safe to commit (treat as API contract) OR gitignore (treat as derived output).

declare module "@trailblaze/scripting" {
  interface TrailblazeToolMap {
    /**
     * Executes a shell command in the Android device's shell environment. Returns combined stdout/stderr.
     *
     * @trailblazeHiddenFromLlm
     * @trailblazeNotRecordable
     */
    android_adbShell: {
      args: {
        command: unknown[];
        runAs?: string;
      };
      result: string;
    };

    /**
     * Sends a broadcast intent to the connected Android device.
     *
     * @trailblazeHiddenFromLlm
     * @trailblazeNotRecordable
     */
    android_sendBroadcast: {
      args: {
        action: string;
        componentPackage: string;
        componentClass: string;
        extras?: unknown[];
      };
      result: string;
    };

    /**
     * Enable demo mode on the device, freezing the clock so it doesn't change.
     *
     * @trailblazeHiddenFromLlm
     */
    android_systemUiDemoMode: {
      args: {
        /** If we should enable demo mode on the device. */
        enable?: boolean;
      };
      result: string;
    };

    /**
     * Calculate the actual and expected values from the current screen state and assert they are equivalent.
     */
    assertEquals: {
      args: {
        actual: string;
        expected: string;
      };
      result: string;
    };

    /**
     * Calculate the result of an expression and compare it to the expected output value.
     */
    assertMath: {
      args: {
        expression: string;
        expected: string;
      };
      result: string;
    };

    /**
     * Calculate the actual and expected values from the current screen state and assert they are NOT equivalent.
     */
    assertNotEquals: {
      args: {
        actual: string;
        expected: string;
      };
      result: string;
    };

    /**
     * Interpolate the natural-language prompt with any included variables, then use the result to verify
     * the current state of the screen with AI.
     */
    assertWithAi: {
      args: {
        prompt: string;
      };
      result: string;
    };

    /**
     * Dump any of the remembered values from the agent's memory. Useful for debugging tests that
     * remember data from one screen state and compare it to a later screen state.
     */
    dumpMemory: {
      args: Record<string, never>;
      result: string;
    };

    /**
     * Hide the keyboard on the screen. Use after entering text into an input field.
     */
    hideKeyboard: {
      args: Record<string, never>;
      result: string;
    };

    /**
     * Type characters into the currently focused text field.
     * - NOTE: If the text field is not focused, tap on it first.
     * - NOTE: If the field already contains text you want to replace, use eraseText first.
     * - NOTE: After typing, consider closing the soft keyboard to avoid issues with the app.
     */
    inputText: {
      args: {
        /** The text to match on. This is required.
NOTE:
- The text can be a regular expression.
- If more than one view matches the text, other optional properties are required to disambiguate. */
        text: string;
        reasoning?: string;
        hideKeyboardAfter?: boolean;
      };
      result: string;
    };

    /**
     * Open an app on the device as if a user tapped on its icon in the launcher.
     */
    launchApp: {
      args: {
        /** The package name of the app to launch. Example: 'com.example.app' */
        appId: string;
        /** Available App Launch Modes:
- "REINSTALL" (Default if unspecified) will launch the app as if it was just installed and never run on the device before.
- "RESUME" will launch the app like you would from the apps launcher.  If the app was in memory, it'll pick up where it left off.
- "FORCE_RESTART" will force stop the application and then launch the app like you would from the app launcher. */
        launchMode?: "REINSTALL" | "RESUME" | "FORCE_RESTART";
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Clears all data for the specified app, resetting it to a fresh state.
     *
     * @trailblazeHiddenFromLlm
     */
    mobile_clearAppData: {
      args: {
        /** The app id to clear (Android package id or iOS bundle id, e.g. 'com.android.deskclock'). */
        appId: string;
      };
      result: string;
    };

    /**
     * Returns a JSON object with the list of installed app ids on the current mobile device.
     *
     * @trailblazeHiddenFromLlm
     */
    mobile_listInstalledApps: {
      args: Record<string, never>;
      result: string;
    };

    /**
     * Pastes the current clipboard contents into the focused text field.
     */
    mobile_pasteClipboard: {
      args: Record<string, never>;
      result: string;
    };

    /**
     * Sets the device clipboard to the specified text.
     */
    mobile_setClipboard: {
      args: {
        /** The text to place on the clipboard. */
        text: string;
      };
      result: string;
    };

    /**
     * Toggles the device to be offline (airplane mode) or online (connected).
     * Use this tool to control network connectivity for the device.
     */
    networkConnection: {
      args: {
        /** Whether the device should be connected or disconnected to the network. */
        connected: boolean;
      };
      result: string;
    };

    /**
     * Use this tool to report the status of the current objective.
     * First determine if all of the objective's goals have been met, and if they have not return an 'in_progress' status.
     * If all of the goals have been met successfully, return a 'completed' status.
     * If you have tried multiple options to complete the objective and are still unsuccessful, then return a 'failed' status.
     * Returning 'failed' should be a last resort once all options have been tested.
     */
    objectiveStatus: {
      args: {
        /** A message explaining what was accomplished or the current progress for this objective */
        explanation: string;
        /** Status of this objective: 'IN_PROGRESS' (still working on it), 'COMPLETED' (fully done), or 'FAILED' */
        status: "IN_PROGRESS" | "COMPLETED" | "FAILED";
      };
      result: string;
    };

    /**
     * Opens the browser to the provided url.
     */
    openUrl: {
      args: {
        /** The URL to open that starts with https */
        url: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Press a special key that isn't used for regular text input. Examples:
     * - BACK: navigate to the previous page or state (Android only).
     * - ENTER: submit the current form or text input.
     * - HOME: go to the device's home screen / send the current app to the background.
     * - BACKSPACE: delete the character before the caret in the currently focused field.
     * - TAB: move focus to the next field.
     * - ESCAPE: dismiss the keyboard or current modal.
     */
    pressKey: {
      args: {
        keyCode: "BACK" | "ENTER" | "HOME" | "BACKSPACE" | "TAB" | "ESCAPE";
      };
      result: string;
    };

    /**
     * Find a number on the current screen using the natural-language prompt, then save it under the
     * variable name for future test operations.
     */
    rememberNumber: {
      args: {
        prompt: string;
        variable: string;
      };
      result: string;
    };

    /**
     * Find text on the current screen using the natural-language prompt, then save it under the
     * variable name for future test operations.
     */
    rememberText: {
      args: {
        prompt: string;
        variable: string;
      };
      result: string;
    };

    /**
     * Remember some data about the current screen using the natural-language prompt, then save it under
     * the variable name for future test operations.
     */
    rememberWithAi: {
      args: {
        prompt: string;
        variable: string;
      };
      result: string;
    };

    /**
     * Scrolls the screen in the specified direction until an element containing the provided text becomes visible
     * in the view hierarchy. The text does not need to be an exact match - it will find elements where the 
     * provided text appears anywhere within the element's text.
     * 
     * The text argument is required. Only provide additional fields if multiple elements contain the same text.
     * In this case the additional fields will be used to identify the specific view to expect to be visible while scrolling.
     */
    scrollUntilTextIsVisible: {
      args: {
        /** Text to search for while scrolling. */
        text: string;
        /** The element id to scroll until. REQUIRED: 'text' and/or 'id' parameter. */
        id?: string;
        /** A 0-based index to disambiguate multiple views with the same text. Default is '0'. */
        index?: number;
        /** Direction to scroll. Default is 'DOWN'. */
        direction?: "UP" | "DOWN" | "RIGHT" | "LEFT";
        /** Percentage of element visible in viewport. Default is '100'. */
        visibilityPercentage?: number;
        /** If it will attempt to stop scrolling when the element is closer to the screen center. Default is 'false'. */
        centerElement?: boolean;
        /** Which part of the screen to scroll from. Default is 'CENTER'. */
        scrollStartPosition?: "CENTER" | "TOP" | "BOTTOM";
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Enable additional tool sets for device interaction. By default, only core tools (tap, input text) are available.
     * Use this to enable more tools when needed. You can enable multiple tool sets at once.
     * Call with an empty list to reset to only the core tools.
     * The available toolset IDs are listed in your system prompt.
     *
     * @trailblazeNotRecordable
     */
    setActiveToolSets: {
      args: {
        /** The list of toolset IDs to enable (e.g. ['navigation', 'text-editing']). Core tools are always included. */
        toolSetIds: unknown[];
      };
      result: string;
    };

    /**
     * Swipe the screen in the specified direction to navigate long lists or pages. Start and end points
     * are calculated automatically from the direction and screen dimensions.
     */
    swipe: {
      args: {
        /** The direction of the finger swipe gesture (not the scroll direction).
To see more content BELOW (scroll down), use 'UP' (finger swipes upward).
To see more content ABOVE (scroll up), use 'DOWN' (finger swipes downward).
Default is 'DOWN'. */
        direction?: "UP" | "DOWN" | "RIGHT" | "LEFT";
        /** The text value to swipe on. If not provided, the swipe will be performed on the center of the screen. */
        swipeOnElementText?: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Take a snapshot of the current page and save it under the provided screen name.
     */
    takeSnapshot: {
      args: {
        /** Name for the screen being captured (e.g., 'login_screen', 'payment_confirmation'). */
        screenName: string;
        /** Optional description of what this snapshot captures or why it was taken. */
        description?: string;
      };
      result: string;
    };

    /**
     * Tap an element by its ref ID from the snapshot. Use the short hash ref shown in square brackets (e.g., y778 from [y778] "Network & internet"). These refs are stable across captures of the same screen.
     *
     * @trailblazeNotRecordable
     */
    tap: {
      args: {
        /** The element ref from the snapshot (e.g., 'y778') */
        ref: string;
        /** Set to true for a long press instead of a tap. */
        longPress?: boolean;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Tap or long press on the UI at the provided coordinates.
     */
    tapOnPoint: {
      args: {
        /** The center X coordinate for the clickable element */
        x: number;
        /** The center Y coordinate for the clickable element */
        y: number;
        /** A standard tap is default, but return 'true' to perform a long press instead. */
        longPress?: boolean;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Wait for a specified amount of time. Use when you see a loading screen — prefer this over
     * pressing the back button.
     */
    wait: {
      args: {
        /** Unit: seconds. Default Value: 5 seconds. */
        timeToWaitInSeconds?: number;
      };
      result: string;
    };

    /**
     * Injects a set of cookies into the current browser context. Pass [cookiesJson] as a JSON
     * string in Playwright's storage-state cookie array shape, e.g.:
     * 
     *   [{"name":"sid","value":"abc","domain":".example.com","path":"/","httpOnly":true,"secure":true,"sameSite":"Lax"}]
     * 
     * Typically used to replay a previously-saved authenticated session so a trail can skip a full
     * UI login. Pair with web_getStorageState (for capture) and web_navigate (to drive to the
     * authenticated landing page after applying).
     */
    web_applyCookies: {
      args: {
        /** JSON array of cookies in Playwright's storage-state cookie shape. May be the full storageState JSON object (in which case the `cookies` field is read), or the bare cookies array. */
        cookiesJson?: string;
      };
      result: string;
    };

    /**
     * Assert that a specific event name appeared in the network traffic captured during this session.
     * 
     * Use this to verify that instrumentation signals, analytics events, or user-journey tracking
     * calls actually fired when a flow was completed. The check scans request URLs and request bodies
     * (both inlined text and on-disk blobs) for the given event name string.
     * 
     * Only outgoing requests (REQUEST_START phase) are checked so each network exchange is counted
     * once regardless of how many response events accompany it.
     * 
     * The tool polls up to the configured timeout so it is safe to call immediately after a UI action
     * without waiting for the browser to flush the analytics beacon. At least one scan always runs
     * regardless of timeoutMs so passing timeoutMs=0 performs a single immediate check.
     * 
     * This is a test assertion — it will fail the trail if the event is not found in the network log.
     * 
     * Example uses:
     * - Verify a user-journey signal fired: eventName="adjust-stock"
     * - Verify an analytics call was made: eventName="checkout-started"
     */
    web_assertNetworkEvent: {
      args: {
        /** The event name to search for in captured network traffic. Matched against request URLs and request body text (case-insensitive). Must not be blank. */
        eventName: string;
        /** Maximum milliseconds to wait for the event to appear in captured traffic. Defaults to 5000. Increase for slow analytics pipelines. One complete scan always runs before the timeout is enforced. */
        timeoutMs?: number;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Click on a web element identified by its element ID, ARIA descriptor, or CSS selector.
     * Use the element ID from the page elements list (e.g., 'e5'), an ARIA descriptor (e.g., 'button "Submit"'),
     * or a CSS selector prefixed with 'css=' (e.g., 'css=#my-button', 'css=[data-testid="submit"]').
     */
    web_click: {
      args: {
        /** Element ID (e.g., 'e5'), ARIA descriptor (e.g., 'button "Submit"'), or CSS selector with css= prefix (e.g., 'css=#my-id', 'css=[data-testid="btn"]'). */
        ref?: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Returns the current page's URL as a plain string. Useful for asserting where a navigation
     * ended up after redirects (e.g. detecting a bounce to `/login` when replaying an expired
     * session).
     */
    web_currentUrl: {
      args: Record<string, never>;
      result: string;
    };

    /**
     * Executes a JavaScript expression in the current page context and returns the result as a
     * string. Internal framework utility — not exposed to the LLM and not captured in trail
     * recordings; available for host-side composition only.
     *
     * @trailblazeHiddenFromLlm
     * @trailblazeNotRecordable
     */
    web_evaluate: {
      args: {
        /** JavaScript expression or IIFE. Use `(() => { ... })()` shape if you need statements. */
        script: string;
      };
      result: string;
    };

    /**
     * INTERNAL — fills a form field with a value that must NOT be logged (passwords, tokens, OTPs).
     * Prefer plain web_type for any value that isn't sensitive, since the LLM-facing recording is
     * more useful when the value is visible. Use only from scripted tools where the value is loaded
     * from a trusted source (secrets store, fixture file, etc.).
     */
    web_fillSecret: {
      args: {
        /** Element ID, ARIA descriptor (e.g., 'textbox "Password"'), or CSS selector with css= prefix. */
        ref: string;
        /** The secret value to fill. Never logged anywhere on the host side. */
        value: string;
      };
      result: string;
    };

    /**
     * Returns the current browser context's storage state (cookies + per-origin localStorage) as a
     * JSON string in Playwright's standard format. Callers typically persist this to disk so a
     * later session can be replayed via web_applyCookies instead of running a full login flow.
     */
    web_getStorageState: {
      args: Record<string, never>;
      result: string;
    };

    /**
     * Hover over a web element identified by its element ID, ARIA descriptor, or CSS selector.
     * Useful for triggering hover states, tooltips, or dropdown menus.
     */
    web_hover: {
      args: {
        /** Element ID (e.g., 'e5'), ARIA descriptor (e.g., 'link "About"'), or CSS selector with css= prefix (e.g., 'css=#my-id'). */
        ref?: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Navigate the browser to a URL, or go back/forward in browser history.
     * Use action GOTO (default) with a url to navigate to a new page.
     * Use action BACK or FORWARD to move through browser history.
     * Relative file paths (e.g., 'sample-app/index.html') are resolved from the working directory.
     */
    web_navigate: {
      args: {
        /** GOTO navigates to a URL, BACK/FORWARD moves through browser history. */
        action?: "GOTO" | "BACK" | "FORWARD";
        /** The URL to navigate to. Required when action is GOTO. Supports full URLs (https://..., file://...) or relative file paths. */
        url?: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Press a keyboard key or key combination.
     * Supports keys like 'Enter', 'Tab', 'Escape', 'Backspace', 'ArrowDown', 'ArrowUp',
     * and combinations like 'Control+A', 'Meta+C', 'Shift+Tab'.
     */
    web_pressKey: {
      args: {
        /** The key or key combination to press (e.g., 'Enter', 'Tab', 'Control+A', 'Meta+C'). */
        key: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Request additional detail in the next view hierarchy snapshot.
     * Call this when you need more information than the default compact element list provides.
     * The next turn's view hierarchy will include the requested details for ALL elements,
     * then automatically revert to the compact format on subsequent turns.
     * 
     * Available detail types:
     * - BOUNDS: Include bounding box coordinates {x,y,w,h} for each element.
     *   Useful for spatial reasoning, determining element positions, checking viewport visibility,
     *   or disambiguating visually similar elements by location.
     * - CSS_SELECTORS: Include CSS selectors for elements and surface hidden elements.
     *   Adds [css=...] annotations to existing elements that have an HTML id or data-testid.
     *   Also discovers elements that are invisible in the default compact list (e.g., unnamed
     *   divs with id or data-testid attributes) and lists them with their CSS selectors.
     *   Use the css= prefix in ref fields to target these elements (e.g., ref: 'css=#my-panel').
     * - OFFSCREEN_ELEMENTS: Include all elements regardless of viewport position.
     *   By default, elements outside the viewport are filtered out to save tokens. Request this
     *   to see all elements with offscreen ones annotated as (offscreen). Useful when you need
     *   to find elements that require scrolling to reach.
     * - OCCLUDED_ELEMENTS: Include elements visually covered by something on top (modal,
     *   popup, toast, autocomplete dropdown). By default these are filtered out because clicks
     *   on them time out — Playwright's actionability check refuses to fire on a non-topmost
     *   element. Request this when you suspect a popup/modal is hiding the elements you need
     *   and you want to see what's underneath before deciding whether to dismiss the overlay.
     *
     * @trailblazeNotRecordable
     */
    web_requestDetails: {
      args: {
        /** List of detail types to include in the next view hierarchy. Supported: BOUNDS, CSS_SELECTORS, OFFSCREEN_ELEMENTS, OCCLUDED_ELEMENTS (or any combination). Example: ["OFFSCREEN_ELEMENTS"] to see all elements including those outside the viewport. */
        include: unknown[];
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Resize the browser viewport to the given dimensions.
     * 
     * Use to test responsive CSS at different breakpoints (e.g., 375x812 for phone,
     * 768x1024 for tablet). Does NOT change User-Agent or device emulation flags —
     * pages that UA-sniff still see desktop Chrome. For full mobile emulation set
     * the device's profile at creation time, not via this tool.
     */
    web_resize: {
      args: {
        /** Width of the viewport in CSS pixels. Must be positive. */
        width: number;
        /** Height of the viewport in CSS pixels. Must be positive. */
        height: number;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Scroll the page or a specific container in the specified direction.
     * When ref is provided, scrolls within that container (e.g., a sidebar or panel) by moving the
     * mouse to its center first. When ref is omitted, scrolls the full page.
     */
    web_scroll: {
      args: {
        /** Direction to scroll. UP/DOWN for vertical, LEFT/RIGHT for horizontal. */
        direction?: "UP" | "DOWN" | "LEFT" | "RIGHT";
        /** Number of pixels to scroll. Defaults to 500. */
        amount?: number;
        /** Element reference for the container to scroll within: ARIA descriptor (e.g., 'navigation "Sidebar"'), element ID (e.g., 'e5'), or CSS selector with css= prefix (e.g., 'css=#scrollable-panel'). When omitted, scrolls the full page. */
        ref?: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Select one or more options from a <select> dropdown element identified by its element ID, ARIA descriptor, or CSS selector.
     * Provide the option values or labels to select.
     */
    web_selectOption: {
      args: {
        /** The option values or visible text labels to select. */
        values: unknown[];
        /** Element ID (e.g., 'e5'), ARIA descriptor (e.g., 'combobox "Category"'), or CSS selector with css= prefix (e.g., 'css=#my-select'). */
        ref?: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Take a snapshot of the current page state and save it with the provided screen name.
     * This captures a screenshot and the page's accessibility tree for logging and debugging.
     */
    web_snapshot: {
      args: {
        /** Name for the screen being captured (e.g., 'login_page', 'dashboard'). */
        screenName: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Type text into a web input element identified by its element ID, ARIA descriptor, or CSS selector.
     * By default this clears the field first and fills in the new text.
     * Set clearFirst to false to append text instead.
     */
    web_type: {
      args: {
        /** The text to type into the element. */
        text: string;
        /** Element ID (e.g., 'e5'), ARIA descriptor (e.g., 'textbox "Email"'), or CSS selector with css= prefix (e.g., 'css=#email-input'). */
        ref?: string;
        /** If true (default), clear the field before typing. If false, append to existing text. */
        clearFirst?: boolean;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Verify that an element identified by its element ID, ARIA descriptor, or CSS selector is visible on the page.
     * This is a test assertion — it will fail the test if the element is not visible.
     */
    web_verifyElementVisible: {
      args: {
        /** Element ID (e.g., 'e5'), ARIA descriptor (e.g., 'button "Submit"'), or CSS selector with css= prefix (e.g., 'css=#my-element'). */
        ref?: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Verify that a list or group of elements contains the expected items.
     * Checks that each expected item text is visible within the container element.
     */
    web_verifyListVisible: {
      args: {
        /** The expected item texts that should be visible in the list. */
        items: unknown[];
        /** Element ID (e.g., 'e5'), ARIA descriptor (e.g., 'list'), or CSS selector with css= prefix (e.g., 'css=#my-list'). */
        ref?: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Verify that specific text is visible on the current page.
     * This is a test assertion — it will fail the test if the text is not found.
     */
    web_verifyTextVisible: {
      args: {
        /** The text content to verify is visible on the page. */
        text: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Verify the value of an element on the page. Supports checking:
     * - TEXT: the text content of any element
     * - VALUE: the input value of a form field (input, textarea, select)
     * - ATTRIBUTE: the value of an HTML attribute
     */
    web_verifyValue: {
      args: {
        /** The expected value to verify against. */
        expected: string;
        /** Element ID (e.g., 'e5'), ARIA descriptor (e.g., 'textbox "Email"'), or CSS selector with css= prefix (e.g., 'css=#email-input'). */
        ref?: string;
        /** What property of the element to verify. TEXT checks visible text content, VALUE checks form field input values, ATTRIBUTE checks a specific HTML attribute. */
        type?: "TEXT" | "VALUE" | "ATTRIBUTE";
        /** The attribute name to check (required when type is ATTRIBUTE). */
        attribute?: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Wait for a specified number of seconds before continuing.
     * Use this when you need to wait for animations, network requests, or page transitions to complete.
     */
    web_wait: {
      args: {
        /** Number of seconds to wait (e.g., 1, 2, 5). Maximum 30 seconds. */
        seconds?: number;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Wait until the current page's URL matches the given regex pattern. Returns the matched URL.
     * Use after web_navigate or web_click when the navigation is async and the next step depends
     * on the final URL (e.g. waiting for a post-login redirect to settle).
     */
    web_waitForUrl: {
      args: {
        /** Java regex pattern the URL must match (e.g. ".*(dashboard|home|orders).*"). */
        pattern: string;
        /** Maximum time to wait in milliseconds. Defaults to 30000ms. */
        timeoutMs?: number;
      };
      result: string;
    };

    /**
     * Dismiss any visible Wikipedia fundraising / fundraiser banner. Use this
     * whenever the task is to close a banner, dismiss a popup, or clear out
     * Wikipedia's donate prompt. If no banner is currently visible the tool is
     * a no-op that returns successfully, so it's safe to call unconditionally
     * at the start of a flow. Probes with a sub-second visibility check before
     * attempting the click so the no-banner path is near-instant.
     */
    wikipedia_web_dismissBannerIfPresent: {
      args: Record<string, never>;
      result: string;
    };

    /**
     * Open a specific Wikipedia article by its title. Use this whenever the task
     * is to read, open, navigate to, or view a particular Wikipedia article —
     * e.g. "open the Albert Einstein article", "go to the Python (programming
     * language) page", "navigate to the Shakespeare article". Spaces in the
     * title are normalized to underscores (Wikipedia's URL convention) so you
     * can pass the title verbatim. Verifies the article rendered by checking
     * the #firstHeading element is visible.
     */
    wikipedia_web_openArticle: {
      args: {
        /** Article title to open (spaces → underscores in URL). */
        title?: string;
        /** Visible heading text to assert. Defaults to `title`. */
        expectedHeading?: string;
        /** When true (default), tries to close any visible fundraising banner. */
        dismissBanner?: boolean;
      };
      result: string;
    };

    /**
     * Open Wikipedia's Main_Page. Use this when the task asks to navigate to
     * Wikipedia, open Wikipedia, go to the Wikipedia home page, or start from
     * the main Wikipedia page. Loads en.wikipedia.org/wiki/Main_Page and waits
     * for it to render. Optionally dismisses any fundraising banner that's
     * currently showing so subsequent steps don't have to reason about it.
     */
    wikipedia_web_openMainPage: {
      args: {
        /** When true (default), tries to close any visible fundraising banner. */
        dismissBanner?: boolean;
      };
      result: string;
    };

    /**
     * Verify one of Wikipedia's four Main_Page sections is present and visible.
     * Use this whenever the task is to verify a main-page section: "Did you
     * know", "In the news", "On this day", or "From today's featured article"
     * (also known as DYK, ITN, OTD, TFA). Pass the section short code to pick
     * which one. The tool anchors verification on the section's stable wrapper
     * element id (`#mp-dyk` etc.) — which survives Wikipedia's day-to-day copy
     * drift — rather than the visible heading text (which rotates daily).
     */
    wikipedia_web_openMainPageSection: {
      args: {
        /** Section short code: tfa | itn | dyk | otd. */
        section?: string;
        /** Open Main_Page first if not there (default true). */
        ensureOnMainPage?: boolean;
      };
      result: string;
    };

    /**
     * Open a random Wikipedia article via the sidebar's "Random article" link.
     * Use this whenever the task is to navigate to a random article, click
     * Random article, jump to a random page, or surf to an unpredictable
     * article. Verifies that a new article page rendered (its #firstHeading
     * is visible) — the resulting title is non-deterministic so don't try to
     * assert specific heading text afterwards.
     */
    wikipedia_web_openRandomArticle: {
      args: {
        /** Open the main page first if not on Wikipedia. */
        ensureOnWikipedia?: boolean;
      };
      result: string;
    };

    /**
     * Search Wikipedia from the header search box. Use this whenever the task
     * is to search Wikipedia for something — e.g. "search for Albert Einstein",
     * "look up Python on Wikipedia", "find articles about Mount Everest". Types
     * the query into the header search input, submits the form, and verifies
     * the resulting article's first heading. Pass `openFirstResult=false` to
     * only type the query without submitting (useful for autocomplete-suggestion
     * tests).
     */
    wikipedia_web_searchAndOpenFirstResult: {
      args: {
        /** Query to type into the search box. */
        query?: string;
        /** Heading text to assert on the opened article. Defaults to `query`. */
        expectedHeading?: string;
        /** Submit the search form (default true). */
        openFirstResult?: boolean;
      };
      result: string;
    };

    /**
     * Search Wikipedia for a topic AND verify the resulting article is
     * well-formed — heading + body, optionally References — in a single tool
     * call. Use this whenever the task combines "search for X" with "verify
     * the article rendered correctly", e.g. "search Wikipedia for Python and
     * confirm the article loaded with a body and References section". Composes
     * the existing `wikipedia_web_searchAndOpenFirstResult` and
     * `wikipedia_web_verifyArticleStructure` tools so callers get both behaviors
     * with one round-trip.
     */
    wikipedia_web_searchAndVerify: {
      args: {
        /** Query to type into the header search box. */
        query?: string;
        /** Heading text to assert on the opened article. Defaults to `query`, which works for exact-match articles like "Python (programming language)". */
        expectedHeading?: string;
        /** Whether to also scroll-and-assert the References section is present. Defaults to false because not every article has one. */
        requireReferences?: boolean;
      };
      result: string;
    };

    /**
     * Open the same Wikipedia article in a different language. Use this
     * whenever the task is to switch language, view in another language, or
     * read the Spanish/French/German/Japanese/etc. version of a Wikipedia
     * article. Routes directly to the matching language subdomain
     * (`es.wikipedia.org`, `fr.wikipedia.org`, …) rather than driving through
     * the in-page language picker (which varies a lot across skins). Verifies
     * the destination article's first heading is visible.
     */
    wikipedia_web_switchArticleLanguage: {
      args: {
        /** English article title. */
        title?: string;
        /** Wikipedia language code (`es`, `fr`, `zh-min-nan`, …). */
        languageCode?: string;
        /** Visible heading text in the localized article. */
        expectedHeading?: string;
      };
      result: string;
    };

    /**
     * Verify the currently loaded page is a well-formed Wikipedia article. Use
     * this whenever the task is to verify an article's structure or layout —
     * confirm a Wikipedia article rendered, check that an article has body
     * content, confirm it has a References section, or sanity-check that
     * navigation actually landed on an article (not a search-results or
     * disambiguation page). Asserts #firstHeading is visible, the body wrapper
     * is visible, and optionally scrolls to confirm the "References" section
     * is present.
     */
    wikipedia_web_verifyArticleStructure: {
      args: {
        /** Visible text to assert in #firstHeading. */
        expectedHeading?: string;
        /** Scroll-to-bottom + assert References heading (default true). */
        requireReferences?: boolean;
      };
      result: string;
    };
  }
}

export {};
