// GENERATED BY TRAILBLAZE DAEMON. DO NOT EDIT.
// Re-runs on daemon restart. Idempotent — content-stable across restarts of the same toolset.
// Safe to commit (treat as API contract) OR gitignore (treat as derived output).

declare module "@trailblaze/scripting" {
  interface TrailblazeToolMap {
    /**
     * Executes a shell command in the Android device's shell environment. Returns combined stdout/stderr.
     *
     * @trailblazeHiddenFromLlm
     * @trailblazeNotRecordable
     */
    android_adbShell: {
      args: {
        command: unknown[];
        runAs?: string;
      };
      result: string;
    };

    /**
     * Sends a broadcast intent to the connected Android device.
     *
     * @trailblazeHiddenFromLlm
     * @trailblazeNotRecordable
     */
    android_sendBroadcast: {
      args: {
        action: string;
        componentPackage: string;
        componentClass: string;
        extras?: unknown[];
      };
      result: string;
    };

    /**
     * Enable demo mode on the device, freezing the clock so it doesn't change.
     *
     * @trailblazeHiddenFromLlm
     */
    android_systemUiDemoMode: {
      args: {
        /** If we should enable demo mode on the device. */
        enable?: boolean;
      };
      result: string;
    };

    /**
     * Asserts that an element with the provided text is NOT visible on the screen. The text argument is required.
     * Only provide additional fields if the text provided exactly matches elsewhere on the screen.
     * Only use this tool if the user is explicitly asking to verify an element that is a TextView, Button, or any views that can display text.
     * IF the view that is being referenced does not display text, DO NOT use this tool.
     * In this case, the additional fields will be used to identify the specific view to assert visibility for.
     * 
     * NOTE:
     * - This will wait for the item to appear if it is not visible yet.
     * - You may need to scroll down the page or close the keyboard if it is not visible in the screenshot.
     * - Use this tool whenever an objective begins with the word expect, verify, confirm, or assert (case-insensitive).
     */
    assertNotVisibleWithText: {
      args: {
        /** The text to match on. This is required.
NOTE:
- The text can be a regular expression.
- If more than one view matches the text, other optional properties are required to disambiguate. */
        text: string;
        /** 0-based index of the view to select among those that match all other criteria. */
        index?: number;
        /** Regex for selecting the view by id. This is helpful to disambiguate when multiple views have the same text. */
        id?: string;
        enabled?: boolean;
        selected?: boolean;
      };
      result: string;
    };

    /**
     * Assert an element is visible on screen by its ref ID from the snapshot. Use the short hash ref shown in square brackets (e.g., y778 from [y778] "Network & internet"). These refs are stable across captures of the same screen.
     */
    assertVisible: {
      args: {
        /** The element ref from the snapshot (e.g., 'y778') */
        ref: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Add a new phone number to an existing iOS contact. Use this whenever the
     * task is to add a phone, attach a number to a contact, edit a contact to
     * include a phone, or update a contact with a new number. Opens the contact,
     * enters edit mode, taps "add phone", types the number, and saves. Verifies
     * the contact's detail screen renders after the save round-trip.
     */
    contacts_ios_addPhoneNumber: {
      args: {
        /** Contact whose detail screen we edit. */
        name?: string;
        /** Phone number to type. Formatting preserved verbatim. */
        phoneNumber?: string;
      };
      result: string;
    };

    /**
     * Create a brand-new contact in the iOS Contacts app. Use this whenever the
     * task is to add a contact, create a contact, save a new person, or otherwise
     * populate the contacts list with someone new. Opens the new-contact draft,
     * types first + last name (and optionally a phone number), and saves. Verifies
     * the save round-trip completed by asserting the contact's full name is
     * visible on the post-save detail screen iOS navigates to.
     */
    contacts_ios_createContact: {
      args: {
        /** First name to type. */
        firstName?: string;
        /** Last name to type. */
        lastName?: string;
        /** Phone number to type. Formatting (spaces, dashes, parens) is preserved verbatim — iOS does its own visual reformat after Save. */
        phoneNumber?: string;
      };
      result: string;
    };

    /**
     * Delete a contact from the iOS Contacts app, by name. Use this whenever the
     * task is to delete a contact, remove a person from Contacts, or clean up a
     * contact created by a previous step. Idempotent — if the contact doesn't
     * exist the tool returns successfully without doing anything, so it's safe to
     * use as a teardown step. Confirms the action-sheet "Delete Contact" prompt
     * automatically.
     */
    contacts_ios_deleteContact: {
      args: {
        /** Visible name of the contact to delete. */
        name?: string;
      };
      result: string;
    };

    /**
     * Dismiss any iOS soft-keyboard that's left visible. Use this whenever the task
     * is to close the keyboard, hide the keyboard, dismiss the search, or clear
     * the on-screen typing affordance. If no keyboard is currently visible the
     * tool is a no-op that returns successfully, so it's safe to call
     * unconditionally between steps that type into a field and steps that need to
     * tap something the keyboard would otherwise occlude.
     */
    contacts_ios_dismissKeyboardIfPresent: {
      args: Record<string, never>;
      result: string;
    };

    /**
     * Open the iOS Contacts app from a cold start. Use this when the task is to
     * launch Contacts, open the Contacts app, go to Contacts, or otherwise begin
     * a Contacts flow. Force-restarts the app so a stale draft or in-progress
     * search from a prior run doesn't leak in. Verifies the contacts list root
     * rendered ("Contacts" navbar title visible). Optionally dismisses any leftover
     * keyboard so the next step sees the full list.
     */
    contacts_ios_openApp: {
      args: {
        /** When true (default), tries to dismiss any keyboard left over from a prior run by tapping the search/cancel chip. Safe to set false if you know the app launches into a clean state. */
        dismissKeyboard?: boolean;
      };
      result: string;
    };

    /**
     * Open a specific contact by name from the iOS Contacts list. Use this whenever
     * the task is to open a contact, view a contact, navigate to someone's
     * contact card, or look up a particular person — e.g. "open the John Appleseed
     * contact", "go to Albert Einstein's contact card". Verifies the contact's
     * detail screen rendered by asserting the contact name is visible in the
     * navbar. If the contact doesn't exist the underlying search throws — callers
     * who want a "create if missing" pattern should wrap this with a `tryOrFalse`.
     */
    contacts_ios_openContact: {
      args: {
        /** Visible name of the contact to open (e.g. "Albert Einstein"). */
        name?: string;
        /** Visible text to assert on the contact detail screen after opening. Defaults to `name`, which works for the common case where the contact's display name is what shows in the navbar. */
        expectedHeading?: string;
      };
      result: string;
    };

    /**
     * Search Contacts for a name AND verify the resulting contact's detail screen
     * is well-formed in a single tool call. Use this whenever the task combines
     * "search for X" with "verify the contact has Y", e.g. "search for Albert
     * Einstein and confirm the contact has a phone number". Composes the
     * existing `contacts_ios_searchContacts` and
     * `contacts_ios_verifyContactStructure` tools so callers get both behaviors
     * with one round-trip.
     */
    contacts_ios_searchAndVerify: {
      args: {
        /** Name to search for. */
        query?: string;
        /** Visible name expected on the opened contact's detail screen. Defaults to `query`; pass explicitly when the query is a prefix and the destination row carries a fuller name. */
        expectedName?: string;
        /** Optional list of field labels the contact must surface. Forwarded to `contacts_ios_verifyContactStructure`. Empty list skips field assertions. */
        requireFields?: string[];
      };
      result: string;
    };

    /**
     * Search the iOS Contacts list for a name and (optionally) open the first
     * matching contact. Use this whenever the task is to search Contacts for a
     * person, look up a contact by name, find someone in Contacts, or jump to a
     * known contact's detail screen. Handles the iOS pull-down-to-reveal-search
     * gesture, types the query, and either taps the first match (default) or
     * leaves the search active so the caller can verify the suggestion list. When
     * `openFirstResult: true` and the query yields no matches, throws a
     * descriptive error so callers can distinguish "wrong query" from "wrong row
     * text".
     */
    contacts_ios_searchContacts: {
      args: {
        /** Query to type into the contacts list's pull-down search field. */
        query?: string;
        /** Row text the tool taps after typing the query. Defaults to `query`. Pass this explicitly when the query is a partial prefix of the row's visible label (e.g. `query="alb"` + `rowText="Albert Einstein"`). */
        rowText?: string;
        /** When true (default), taps the first visible matching row to open the contact's detail screen. When false, leaves the search active so a caller can verify the autocomplete-style suggestion list itself. */
        openFirstResult?: boolean;
      };
      result: string;
    };

    /**
     * Verify the currently-open iOS contact detail screen conforms to an expected
     * shape — name heading visible, plus an optional list of required field
     * labels ("phone", "email", "home", etc.). Use this whenever the task is to
     * confirm a contact rendered correctly, check a contact has certain fields,
     * or assert a contact's shape. Pass an empty `requireFields` list for a
     * lightweight "did the detail screen render?" check.
     */
    contacts_ios_verifyContactStructure: {
      args: {
        /** Contact name to assert in the navbar / heading. */
        name?: string;
        /** Optional list of additional field labels the contact must surface — common values: "phone", "mobile", "email", "home", "work". Each entry is passed to `assertVisibleWithAccessibilityText` as the `textRegex` value, so it's interpreted as a regex against accessibility text (case-sensitive by default — wrap with `(?i)` for case-insensitive). Empty list (the default) skips the field-presence assertions. */
        requireFields?: string[];
      };
      result: string;
    };

    /**
     * Hide the keyboard on the screen. Use after entering text into an input field.
     */
    hideKeyboard: {
      args: Record<string, never>;
      result: string;
    };

    /**
     * Type characters into the currently focused text field.
     * - NOTE: If the text field is not focused, tap on it first.
     * - NOTE: If the field already contains text you want to replace, use eraseText first.
     * - NOTE: After typing, consider closing the soft keyboard to avoid issues with the app.
     */
    inputText: {
      args: {
        /** The text to match on. This is required.
NOTE:
- The text can be a regular expression.
- If more than one view matches the text, other optional properties are required to disambiguate. */
        text: string;
        reasoning?: string;
        hideKeyboardAfter?: boolean;
      };
      result: string;
    };

    /**
     * Open an app on the device as if a user tapped on its icon in the launcher.
     */
    launchApp: {
      args: {
        /** The package name of the app to launch. Example: 'com.example.app' */
        appId: string;
        /** Available App Launch Modes:
- "REINSTALL" (Default if unspecified) will launch the app as if it was just installed and never run on the device before.
- "RESUME" will launch the app like you would from the apps launcher.  If the app was in memory, it'll pick up where it left off.
- "FORCE_RESTART" will force stop the application and then launch the app like you would from the app launcher. */
        launchMode?: "REINSTALL" | "RESUME" | "FORCE_RESTART";
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Clears all data for the specified app, resetting it to a fresh state.
     *
     * @trailblazeHiddenFromLlm
     */
    mobile_clearAppData: {
      args: {
        /** The app id to clear (Android package id or iOS bundle id, e.g. 'com.android.deskclock'). */
        appId: string;
      };
      result: string;
    };

    /**
     * Returns a JSON object with the list of installed app ids on the current mobile device.
     *
     * @trailblazeHiddenFromLlm
     */
    mobile_listInstalledApps: {
      args: Record<string, never>;
      result: string;
    };

    /**
     * Pastes the current clipboard contents into the focused text field.
     */
    mobile_pasteClipboard: {
      args: Record<string, never>;
      result: string;
    };

    /**
     * Sets the device clipboard to the specified text.
     */
    mobile_setClipboard: {
      args: {
        /** The text to place on the clipboard. */
        text: string;
      };
      result: string;
    };

    /**
     * Toggles the device to be offline (airplane mode) or online (connected).
     * Use this tool to control network connectivity for the device.
     */
    networkConnection: {
      args: {
        /** Whether the device should be connected or disconnected to the network. */
        connected: boolean;
      };
      result: string;
    };

    /**
     * Use this tool to report the status of the current objective.
     * First determine if all of the objective's goals have been met, and if they have not return an 'in_progress' status.
     * If all of the goals have been met successfully, return a 'completed' status.
     * If you have tried multiple options to complete the objective and are still unsuccessful, then return a 'failed' status.
     * Returning 'failed' should be a last resort once all options have been tested.
     */
    objectiveStatus: {
      args: {
        /** A message explaining what was accomplished or the current progress for this objective */
        explanation: string;
        /** Status of this objective: 'IN_PROGRESS' (still working on it), 'COMPLETED' (fully done), or 'FAILED' */
        status: "IN_PROGRESS" | "COMPLETED" | "FAILED";
      };
      result: string;
    };

    /**
     * Opens the browser to the provided url.
     */
    openUrl: {
      args: {
        /** The URL to open that starts with https */
        url: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Press a special key that isn't used for regular text input. Examples:
     * - BACK: navigate to the previous page or state (Android only).
     * - ENTER: submit the current form or text input.
     * - HOME: go to the device's home screen / send the current app to the background.
     * - BACKSPACE: delete the character before the caret in the currently focused field.
     * - TAB: move focus to the next field.
     * - ESCAPE: dismiss the keyboard or current modal.
     */
    pressKey: {
      args: {
        keyCode: "BACK" | "ENTER" | "HOME" | "BACKSPACE" | "TAB" | "ESCAPE";
      };
      result: string;
    };

    /**
     * Scrolls the screen in the specified direction until an element containing the provided text becomes visible
     * in the view hierarchy. The text does not need to be an exact match - it will find elements where the 
     * provided text appears anywhere within the element's text.
     * 
     * The text argument is required. Only provide additional fields if multiple elements contain the same text.
     * In this case the additional fields will be used to identify the specific view to expect to be visible while scrolling.
     */
    scrollUntilTextIsVisible: {
      args: {
        /** Text to search for while scrolling. */
        text: string;
        /** The element id to scroll until. REQUIRED: 'text' and/or 'id' parameter. */
        id?: string;
        /** A 0-based index to disambiguate multiple views with the same text. Default is '0'. */
        index?: number;
        /** Direction to scroll. Default is 'DOWN'. */
        direction?: "UP" | "DOWN" | "RIGHT" | "LEFT";
        /** Percentage of element visible in viewport. Default is '100'. */
        visibilityPercentage?: number;
        /** If it will attempt to stop scrolling when the element is closer to the screen center. Default is 'false'. */
        centerElement?: boolean;
        /** Which part of the screen to scroll from. Default is 'CENTER'. */
        scrollStartPosition?: "CENTER" | "TOP" | "BOTTOM";
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Enable additional tool sets for device interaction. By default, only core tools (tap, input text) are available.
     * Use this to enable more tools when needed. You can enable multiple tool sets at once.
     * Call with an empty list to reset to only the core tools.
     * The available toolset IDs are listed in your system prompt.
     *
     * @trailblazeNotRecordable
     */
    setActiveToolSets: {
      args: {
        /** The list of toolset IDs to enable (e.g. ['navigation', 'text-editing']). Core tools are always included. */
        toolSetIds: unknown[];
      };
      result: string;
    };

    /**
     * Swipe the screen in the specified direction to navigate long lists or pages. Start and end points
     * are calculated automatically from the direction and screen dimensions.
     */
    swipe: {
      args: {
        /** The direction of the finger swipe gesture (not the scroll direction).
To see more content BELOW (scroll down), use 'UP' (finger swipes upward).
To see more content ABOVE (scroll up), use 'DOWN' (finger swipes downward).
Default is 'DOWN'. */
        direction?: "UP" | "DOWN" | "RIGHT" | "LEFT";
        /** The text value to swipe on. If not provided, the swipe will be performed on the center of the screen. */
        swipeOnElementText?: string;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Take a snapshot of the current page and save it under the provided screen name.
     */
    takeSnapshot: {
      args: {
        /** Name for the screen being captured (e.g., 'login_screen', 'payment_confirmation'). */
        screenName: string;
        /** Optional description of what this snapshot captures or why it was taken. */
        description?: string;
      };
      result: string;
    };

    /**
     * Tap an element by its ref ID from the snapshot. Use the short hash ref shown in square brackets (e.g., y778 from [y778] "Network & internet"). These refs are stable across captures of the same screen.
     *
     * @trailblazeNotRecordable
     */
    tap: {
      args: {
        /** The element ref from the snapshot (e.g., 'y778') */
        ref: string;
        /** Set to true for a long press instead of a tap. */
        longPress?: boolean;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Tap or long press on the UI at the provided coordinates.
     */
    tapOnPoint: {
      args: {
        /** The center X coordinate for the clickable element */
        x: number;
        /** The center Y coordinate for the clickable element */
        y: number;
        /** A standard tap is default, but return 'true' to perform a long press instead. */
        longPress?: boolean;
        reasoning?: string;
      };
      result: string;
    };

    /**
     * Wait for a specified amount of time. Use when you see a loading screen — prefer this over
     * pressing the back button.
     */
    wait: {
      args: {
        /** Unit: seconds. Default Value: 5 seconds. */
        timeToWaitInSeconds?: number;
      };
      result: string;
    };

    /**
     * Executes a JavaScript expression in the current page context and returns the result as a
     * string. Internal framework utility — not exposed to the LLM and not captured in trail
     * recordings; available for host-side composition only.
     *
     * @trailblazeHiddenFromLlm
     * @trailblazeNotRecordable
     */
    web_evaluate: {
      args: {
        /** JavaScript expression or IIFE. Use `(() => { ... })()` shape if you need statements. */
        script: string;
      };
      result: string;
    };
  }
}

export {};
