// GENERATED BY TRAILBLAZE DAEMON. DO NOT EDIT.
// Re-runs on daemon restart. Idempotent — content-stable across restarts of the same toolset.
// Safe to commit (treat as API contract) OR gitignore (treat as derived output).

declare module "@trailblaze/scripting" {
  interface TrailblazeToolMap {
    /**
     * Write a text artifact to a per-session tmp directory on the host machine.
     */
    sampleapp_writeArtifact: {
      args: {
        /** Path under the per-session artifacts directory; must be relative and free of "..". */
        relativePath?: string;
        /** Text contents to write to the artifact file. */
        contents?: string;
      };
      result: string;
    };
  }
}

export {};
