package xyz.block.trailblaze.toolcalls.commands

import ai.koog.agents.core.tools.annotations.LLMDescription
import kotlinx.serialization.Serializable
import maestro.orchestra.AssertConditionCommand
import maestro.orchestra.Command
import maestro.orchestra.Condition
import xyz.block.trailblaze.AgentMemory
import xyz.block.trailblaze.api.TrailblazeElementSelector
import xyz.block.trailblaze.api.TrailblazeNodeSelector
import xyz.block.trailblaze.model.NodeSelectorMode
import xyz.block.trailblaze.toolcalls.MapsToMaestroCommands
import xyz.block.trailblaze.toolcalls.TrailblazeToolClass
import xyz.block.trailblaze.toolcalls.TrailblazeToolExecutionContext
import xyz.block.trailblaze.toolcalls.TrailblazeToolResult
import xyz.block.trailblaze.toolcalls.commands.TrailblazeElementSelectorExt.toMaestroElementSelector
import xyz.block.trailblaze.toolcalls.isSuccess

@Serializable
@TrailblazeToolClass(
  name = "assertVisibleBySelector",
  isForLlm = false,
  isVerification = true,
)
@LLMDescription("Asserts that an element with the provided selector is visible on the screen.")
/**
 *  ----- DO NOT USE GIVE THIS TOOL TO THE LLM -----
 *
 * This is a tool that should be delegated to, not registered to the LLM
 */
data class AssertVisibleBySelectorTrailblazeTool(
  val reason: String? = null,
  /**
   * Legacy Maestro-shape selector. Nullable so post-migration YAMLs (generated by
   * `waypoint migrate-trail`) can carry [nodeSelector] alone with no `selector:`
   * block — the migration goal is zero Maestro selectors on migrated tools, since
   * having both fields creates ambiguity about source-of-truth. At least one of
   * [selector] and [nodeSelector] must be non-null at runtime — the [execute]
   * function enforces this.
   */
  val selector: TrailblazeElementSelector? = null,
  /**
   * Rich driver-native selector generated from [TrailblazeNode] trees.
   * When present, the agent will attempt to use this for richer element matching
   * before falling back to the legacy Maestro command path via [selector].
   */
  val nodeSelector: TrailblazeNodeSelector? = null,
  /**
   * Maximum time (in milliseconds) to wait for the element to become visible. The driver
   * polls the screen until either the element appears or this timeout elapses, so this
   * doubles as a "wait for selector" knob — set it higher when the screen needs time to
   * settle (e.g. an "Authorizing" overlay clearing) before the target text renders.
   *
   * When `null` the call is unopinionated about timeout and each agent applies its own
   * idle/wait policy (per-driver default). The Maestro fallback path ignores this field
   * entirely — Maestro's own assert timeout is always used there.
   */
  val timeoutMs: Long? = null,
) : MapsToMaestroCommands() {
  override fun toMaestroCommands(memory: AgentMemory): List<Command> {
    // Maestro fallback only applies when a legacy selector exists. Post-migration tools
    // carrying only a nodeSelector skip this path entirely (the runtime takes the
    // nodeSelector path in `execute` and never calls super.execute → toMaestroCommands).
    val legacy = selector
      ?: error(
        "AssertVisibleBySelectorTrailblazeTool.toMaestroCommands called with no legacy " +
          "selector — this tool was migrated to nodeSelector-only and shouldn't fall back " +
          "to the Maestro path. Check NodeSelectorMode wiring.",
      )
    return listOf(
      AssertConditionCommand(condition = Condition(visible = legacy.toMaestroElementSelector())),
    )
  }

  override suspend fun execute(
    toolExecutionContext: TrailblazeToolExecutionContext,
  ): TrailblazeToolResult {
    require(selector != null || nodeSelector != null) {
      "AssertVisibleBySelectorTrailblazeTool requires at least one of `selector` or " +
        "`nodeSelector` to be non-null."
    }
    val mode = toolExecutionContext.nodeSelectorMode
    val agent = toolExecutionContext.maestroTrailblazeAgent

    val result = when (mode) {
      NodeSelectorMode.FORCE_LEGACY -> super.execute(toolExecutionContext)
      NodeSelectorMode.FORCE_NODE_SELECTOR -> {
        if (agent != null) {
          val effectiveNodeSelector = nodeSelector
            ?: selector?.toTrailblazeNodeSelector(toolExecutionContext.trailblazeDeviceInfo.platform)
            ?: error("FORCE_NODE_SELECTOR with neither nodeSelector nor selector")
          agent.executeNodeSelectorAssertVisible(
            nodeSelector = effectiveNodeSelector,
            timeoutMs = timeoutMs,
            traceId = toolExecutionContext.traceId,
          ) ?: super.execute(toolExecutionContext)
        } else {
          super.execute(toolExecutionContext)
        }
      }
      NodeSelectorMode.PREFER_NODE_SELECTOR -> {
        if (nodeSelector != null && agent != null) {
          agent.executeNodeSelectorAssertVisible(
            nodeSelector = nodeSelector,
            timeoutMs = timeoutMs,
            traceId = toolExecutionContext.traceId,
          ) ?: super.execute(toolExecutionContext)
        } else {
          super.execute(toolExecutionContext)
        }
      }
    }
    if (result.isSuccess()) {
      // Prefer the original selector's text for a friendly message, but fall back to the
      // nodeSelector's accessibility text if the legacy selector is gone (post-migration).
      val desc = selector?.textRegex
        ?: selector?.idRegex
        ?: nodeSelector?.androidAccessibility?.textRegex
        ?: nodeSelector?.androidAccessibility?.contentDescriptionRegex
        ?: "element"
      return TrailblazeToolResult.Success(message = "Verified '$desc' visible")
    }
    return result
  }
}
