package xyz.block.trailblaze.agent.trail

import kotlinx.coroutines.runBlocking
import org.junit.Test
import xyz.block.trailblaze.agent.ExecutionResult
import xyz.block.trailblaze.agent.RecordedAction
import xyz.block.trailblaze.agent.UiActionExecutor
import xyz.block.trailblaze.logs.model.TraceId
import xyz.block.trailblaze.api.ScreenState
import kotlinx.serialization.json.JsonObject
import xyz.block.trailblaze.agent.Confidence
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Unit tests for [EnhancedRecording] and related classes.
 *
 * Tests recording conditions, recovery strategies, and validation.
 */
class EnhancedRecordingTest {

  // Mock ConditionChecker
  private class MockConditionChecker : ConditionChecker {
    override suspend fun check(
      condition: RecordingCondition,
      screenState: ScreenState,
    ): Boolean {
      return when (condition) {
        is RecordingCondition.ScreenContains -> {
          screenState.viewHierarchy.toString().contains(condition.text)
        }
        is RecordingCondition.ScreenNotContains -> {
          !screenState.viewHierarchy.toString().contains(condition.text)
        }
        is RecordingCondition.CustomCondition -> true
      }
    }
  }

  // Mock UiActionExecutor
  private class MockUiActionExecutor : UiActionExecutor {
    var executeCount = 0
    var shouldFail = false
    
    override suspend fun execute(
      toolName: String,
      args: JsonObject,
      traceId: TraceId?,
    ): ExecutionResult {
      executeCount++
      return if (shouldFail) {
        ExecutionResult.Failure("Mock failure", recoverable = true)
      } else {
        ExecutionResult.Success("Screen after", 100L)
      }
    }
    
    override suspend fun captureScreenState(): ScreenState? = null
  }

  private fun createRecordedAction(
    toolName: String = "tap",
    success: Boolean = true,
  ): RecordedAction = RecordedAction(
    toolName = toolName,
    toolArgs = JsonObject(emptyMap()),
    reasoning = "Test action",
    screenSummaryBefore = "Before screen",
    screenSummaryAfter = "After screen",
    confidence = Confidence.HIGH,
    durationMs = 100,
    success = success,
    errorMessage = null,
  )

  // ====== ENHANCED RECORDING CREATION TESTS ======

  @Test
  fun `should create enhanced recording from actions`() {
    val actions = listOf(
      createRecordedAction("tap"),
      createRecordedAction("scroll"),
    )
    
    val recording = createEnhancedRecording("Login to app", actions)
    
    assertEquals("Login to app", recording.stepPrompt)
    assertEquals(2, recording.actions.size)
    assertNotNull(recording.metadata)
  }

  @Test
  fun `should infer preconditions from first action`() {
    val actions = listOf(
      createRecordedAction("tap"),
    )
    
    val recording = createEnhancedRecording("Test step", actions)
    
    assertTrue(recording.preconditions.isNotEmpty(), "Should infer preconditions")
  }

  @Test
  fun `should infer postconditions from last action`() {
    val actions = listOf(
      createRecordedAction("tap"),
    )
    
    val recording = createEnhancedRecording("Test step", actions)
    
    assertTrue(recording.postconditions.isNotEmpty(), "Should infer postconditions")
  }

  @Test
  fun `should add default recovery strategies`() {
    val actions = listOf(createRecordedAction("tap"))
    
    val recording = createEnhancedRecording("Test step", actions)
    
    assertTrue(recording.recoveryStrategies.isNotEmpty(), "Should have default recovery strategies")
  }

  @Test
  fun `should calculate metadata correctly`() {
    val actions = listOf(
      createRecordedAction("tap"),
      createRecordedAction("tap"),
    )
    
    val recording = createEnhancedRecording("Test", actions)
    
    assertNotNull(recording.metadata.executionDurationMs)
    assertTrue(recording.metadata.executionDurationMs!! > 0)
    assertTrue(recording.metadata.autoGenerated)
  }

  @Test
  fun `should handle empty actions list`() {
    val recording = createEnhancedRecording("Test step", emptyList())
    
    assertEquals("Test step", recording.stepPrompt)
    assertTrue(recording.actions.isEmpty())
  }

  // ====== RECORDING CONDITION TESTS ======

  @Test
  fun `should create ScreenContains condition`() {
    val condition = RecordingCondition.ScreenContains("Login button", caseSensitive = false)
    
    assertEquals("Login button", condition.text)
    assertFalse(condition.caseSensitive)
  }

  @Test
  fun `should create ScreenNotContains condition`() {
    val condition = RecordingCondition.ScreenNotContains("Error", caseSensitive = true)
    
    assertEquals("Error", condition.text)
    assertTrue(condition.caseSensitive)
  }

  @Test
  fun `should create CustomCondition`() {
    val condition = RecordingCondition.CustomCondition("Verify user is logged in")
    
    assertEquals("Verify user is logged in", condition.prompt)
  }

  // ====== RECOVERY STRATEGY TESTS ======

  @Test
  fun `should create OnPopup recovery strategy`() {
    val strategy = RecoveryStrategy.OnPopup(
      method = DismissMethod.BACK_BUTTON,
      maxAttempts = 3,
    )
    
    assertEquals(DismissMethod.BACK_BUTTON, strategy.method)
    assertEquals(3, strategy.maxAttempts)
  }

  @Test
  fun `should create OnError recovery strategy`() {
    val strategy = RecoveryStrategy.OnError(
      action = ErrorAction.RETRY_ONCE,
      maxRetries = 2,
    )
    
    assertEquals(ErrorAction.RETRY_ONCE, strategy.action)
    assertEquals(2, strategy.maxRetries)
  }

  @Test
  fun `should create OnLoading recovery strategy`() {
    val strategy = RecoveryStrategy.OnLoading(
      maxWaitMs = 5000,
      checkIntervalMs = 100,
    )
    
    assertEquals(5000L, strategy.maxWaitMs)
    assertEquals(100L, strategy.checkIntervalMs)
  }

  @Test
  fun `should create OnAdvertisement recovery strategy`() {
    val strategy = RecoveryStrategy.OnAdvertisement(waitForSkip = 5)
    
    assertEquals(5, strategy.waitForSkip)
  }

  @Test
  fun `should create OnUnexpectedScreen recovery strategy`() {
    val strategy = RecoveryStrategy.OnUnexpectedScreen(maxBackPresses = 3)
    
    assertEquals(3, strategy.maxBackPresses)
  }

  // ====== DISMISS METHOD TESTS ======

  @Test
  fun `should have dismiss method enum values`() {
    assertEquals(4, DismissMethod.entries.size)
    assertTrue(DismissMethod.BACK_BUTTON in DismissMethod.entries)
    assertTrue(DismissMethod.TAP_OUTSIDE in DismissMethod.entries)
    assertTrue(DismissMethod.TAP_DISMISS in DismissMethod.entries)
    assertTrue(DismissMethod.TAP_CONFIRM in DismissMethod.entries)
  }

  // ====== ERROR ACTION TESTS ======

  @Test
  fun `should have error action enum values`() {
    assertEquals(4, ErrorAction.entries.size)
    assertTrue(ErrorAction.RETRY_ONCE in ErrorAction.entries)
    assertTrue(ErrorAction.RETRY_MULTIPLE in ErrorAction.entries)
    assertTrue(ErrorAction.SKIP in ErrorAction.entries)
    assertTrue(ErrorAction.FAIL in ErrorAction.entries)
  }

  // ====== VALIDATION RESULT TESTS ======

  @Test
  fun `should track passed and failed steps`() {
    val results = listOf(
      StepValidationResult(0, "Step 0", passed = true),
      StepValidationResult(1, "Step 1", passed = false),
      StepValidationResult(2, "Step 2", passed = true),
    )
    
    val validationResult = ValidationResult(
      success = false,
      stepResults = results,
      durationMs = 1000,
    )
    
    assertEquals(2, validationResult.passedSteps)
    assertEquals(1, validationResult.failedSteps)
  }

  @Test
  fun `should identify steps needing rerecording`() {
    val results = listOf(
      StepValidationResult(0, "Step 0", passed = true, needsRerecording = false),
      StepValidationResult(1, "Step 1", passed = false, needsRerecording = true),
      StepValidationResult(2, "Step 2", passed = true, needsRerecording = true),
    )
    
    val validationResult = ValidationResult(
      success = false,
      stepResults = results,
      durationMs = 1000,
    )
    
    assertEquals(listOf(1, 2), validationResult.stepsNeedingRerecording)
  }

  @Test
  fun `should set success to true when all steps pass`() {
    val results = listOf(
      StepValidationResult(0, "Step 0", passed = true),
      StepValidationResult(1, "Step 1", passed = true),
    )
    
    val validationResult = ValidationResult(
      success = true,
      stepResults = results,
      durationMs = 100,
    )
    
    assertTrue(validationResult.success)
    assertTrue(validationResult.errorMessage == null, "Should have no error message when all pass")
  }

  // ====== STEP VALIDATION RESULT TESTS ======

  @Test
  fun `should track failed preconditions`() {
    val result = StepValidationResult(
      stepIndex = 0,
      stepPrompt = "Test step",
      passed = false,
      failedPreconditions = listOf("Condition A", "Condition B"),
    )
    
    assertEquals(2, result.failedPreconditions.size)
    assertFalse(result.passed)
  }

  @Test
  fun `should track recovery used`() {
    val result = StepValidationResult(
      stepIndex = 0,
      stepPrompt = "Test step",
      passed = true,
      recoveryUsed = "OnPopup.BACK_BUTTON",
    )
    
    assertEquals("OnPopup.BACK_BUTTON", result.recoveryUsed)
  }

  @Test
  fun `should mark for rerecording with reason`() {
    val result = StepValidationResult(
      stepIndex = 0,
      stepPrompt = "Test step",
      passed = false,
      needsRerecording = true,
      rerecordingReason = "Execution failed and recovery exhausted",
    )
    
    assertTrue(result.needsRerecording)
    assertNotNull(result.rerecordingReason)
  }

  // ====== RECORDING VALIDATOR TESTS ======

  @Test
  fun `should validate successful recording`() = runBlocking {
    val recordings = listOf(
      createEnhancedRecording("Step 1", listOf(createRecordedAction())),
    )
    
    val executor = MockUiActionExecutor()
    val checker = MockConditionChecker()
    val validator = RecordingValidator(checker)
    
    val result = validator.validate(recordings, executor)
    
    assertTrue(result.success || result.failedSteps == 0, "Should validate successfully")
  }

  @Test
  fun `should handle execution failure`() = runBlocking {
    val recordings = listOf(
      createEnhancedRecording("Step 1", listOf(createRecordedAction())),
    )
    
    val executor = MockUiActionExecutor().apply { shouldFail = true }
    val checker = MockConditionChecker()
    val validator = RecordingValidator(checker)
    
    val result = validator.validate(recordings, executor)
    
    assertNotNull(result)
    assertEquals(1, result.stepResults.size)
  }

  @Test
  fun `should validate multiple recordings`() = runBlocking {
    val recordings = listOf(
      createEnhancedRecording("Step 1", listOf(createRecordedAction())),
      createEnhancedRecording("Step 2", listOf(createRecordedAction())),
      createEnhancedRecording("Step 3", listOf(createRecordedAction())),
    )
    
    val executor = MockUiActionExecutor()
    val checker = MockConditionChecker()
    val validator = RecordingValidator(checker)
    
    val result = validator.validate(recordings, executor)
    
    assertEquals(3, result.stepResults.size)
  }

  @Test
  fun `should measure validation duration`() = runBlocking {
    val recordings = listOf(
      createEnhancedRecording("Step", listOf(createRecordedAction())),
    )
    
    val executor = MockUiActionExecutor()
    val checker = MockConditionChecker()
    val validator = RecordingValidator(checker)
    
    val result = validator.validate(recordings, executor)
    
    assertTrue(result.durationMs >= 0)
  }

  // ====== DEFAULT CONDITION CHECKER TESTS ======

  @Test
  fun `should create default condition checker`() {
    val checker = DefaultConditionChecker()
    assertNotNull(checker)
  }

  // ====== EDGE CASES ======

  @Test
  fun `should handle recording with no actions`() {
    val recording = createEnhancedRecording("Empty step", emptyList())
    
    assertEquals("Empty step", recording.stepPrompt)
    assertTrue(recording.actions.isEmpty())
    assertNotNull(recording.metadata)
  }

  @Test
  fun `should handle recording with many actions`() {
    val actions = (0..99).map { createRecordedAction("tap") }
    val recording = createEnhancedRecording("Many actions", actions)
    
    assertEquals(100, recording.actions.size)
  }

  @Test
  fun `should handle validation with empty recordings`() = runBlocking {
    val executor = MockUiActionExecutor()
    val checker = MockConditionChecker()
    val validator = RecordingValidator(checker)
    
    val result = validator.validate(emptyList(), executor)
    
    assertTrue(result.success)
    assertEquals(0, result.stepResults.size)
  }

  @Test
  fun `should handle long step prompts`() {
    val longPrompt = "a".repeat(1000)
    val recording = createEnhancedRecording(longPrompt, listOf(createRecordedAction()))
    
    assertEquals(longPrompt, recording.stepPrompt)
  }
}
