package xyz.block.trailblaze.scripting.bundle

import java.io.File
import java.nio.file.AtomicMoveNotSupportedException
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardCopyOption
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicReference

/**
 * Materializes the committed `trailblaze-sdk-bundle.js` (the bundled `@trailblaze/scripting`
 * SDK shipped at [RESOURCE_PATH] inside this module's JVM/AAR resources) onto disk so callers
 * that need a real `File` path — primarily node subprocesses spawned by the inline-script-tool
 * synthesizer, which feed it to `pathToFileURL(...)` — can `import(...)` it without an HTTP hop
 * or an in-memory bridge. The on-device QuickJS path doesn't go through here; it reads the same
 * resource in-process via [BundleRuntimePrelude.SDK_BUNDLE_SOURCE].
 *
 * ### Security & correctness shape
 *
 * Earlier revisions of this code lived inline in the host-side synthesizer and cached the
 * extracted bundle in a content-addressed file under `${java.io.tmpdir}/trailblaze-sdk-bundle/`.
 * That shape carried a TOCTOU/tampering risk: a shared, world-readable temp dir whose cache
 * hit was gated only on file-size let a colocated process (or a stale file from a prior run
 * with different bundle bytes) get executed by node.
 *
 * This implementation closes both holes:
 *
 *  - [Files.createTempDirectory] produces a uniquely-named directory whose permissions are
 *    restricted to the current user (mode 700 on POSIX; ACL-restricted on Windows). No other
 *    user can read or write the extracted file.
 *  - The bundle bytes are written to a sibling staging file and atomically renamed onto the
 *    final path with `ATOMIC_MOVE` + `REPLACE_EXISTING`. No reader ever sees a half-written
 *    file. On filesystems that don't support atomic rename ([AtomicMoveNotSupportedException])
 *    we fall back to a non-atomic move; the staging file lives in our process-scoped 700 dir,
 *    so cross-process tampering during the now-non-atomic replace window is still impossible.
 *  - The extracted [File] is cached in a process-local [AtomicReference] so subsequent calls
 *    return the same path without re-reading the classpath or re-writing disk. There is no
 *    cross-process cache and no on-cache-hit content check — the file we hand back is the file
 *    THIS process wrote a moment ago, not one we found lying around. If the cached file is
 *    externally evicted (OS tmp cleanup, accidental rm), the next call re-extracts to a new
 *    tempDir; the prior tempDir is tracked in [tempDirsToCleanUp] for shutdown-time deletion.
 *  - A single JVM shutdown hook (registered once via [registerShutdownHook]) drains
 *    [tempDirsToCleanUp] on clean exit, so re-extractions don't accumulate hooks. A crashed
 *    JVM leaves the dirs behind, but POSIX tmp dirs get GC'd by the OS and the next JVM gets
 *    fresh unique dirs anyway, so leakage is bounded and harmless.
 */
object SdkBundleResource {

  // Shared root for every name we need: classpath path, extracted filename, tempDir prefix.
  // Kotlin's `const val` supports compile-time string interpolation when every embedded value
  // is itself `const val`, so the three public/private constants below derive from this single
  // source of truth — a future rename of the artifact updates exactly one line.
  private const val BASE_NAME: String = "trailblaze-sdk-bundle"

  /** Filename of the extracted bundle inside its tempDir. Public so callers/tests that need
   *  to identify the file by name (e.g. regex-matching the synthesized wrapper's import path)
   *  share a single source of truth with the extractor. */
  const val FILE_NAME: String = "$BASE_NAME.js"

  /**
   * Classpath path to the bundled `@trailblaze/scripting` SDK JS, generated by the
   * `:trailblaze-scripting-bundle:bundleTrailblazeSdk` Gradle task and committed in-tree
   * (see `build.gradle.kts` for the regen-and-commit workflow).
   *
   * `internal` because the only cross-module consumer of this constant is
   * [BundleRuntimePrelude] (same module). External callers go through [extractToFile] /
   * [FILE_NAME]; tightening visibility prevents accidental coupling on the resource path
   * shape from outside the bundle module.
   */
  internal const val RESOURCE_PATH: String = "trailblaze/scripting/bundle/$FILE_NAME"

  // Prefix passed to `Files.createTempDirectory` so each tempDir is recognizable in `lsof` /
  // tmp listings. Matches the artifact's base name with a trailing `-` separator (which the
  // JDK appends a random suffix onto).
  private const val TEMP_DIR_PREFIX: String = "$BASE_NAME-"

  private val cached = AtomicReference<File?>(null)

  // Every tempDir we ever create lands here. The single shutdown hook (registered the first
  // time we extract) drains the set on JVM exit. ConcurrentHashMap-backed because adds happen
  // under our extraction lock but the shutdown-hook iterator runs unsynchronized with respect
  // to a possible final extraction racing JVM termination.
  private val tempDirsToCleanUp = ConcurrentHashMap.newKeySet<File>()
  private val shutdownHookRegistered = AtomicReference(false)

  /**
   * Returns a [File] whose contents are the SDK bundle JS. The same path is returned on every
   * call within a single JVM unless the cached file is externally deleted, in which case the
   * next call re-extracts to a new path. Throws [IllegalStateException] if the bundle isn't
   * on the classpath — that means this module's JVM jar isn't on the runtime classpath of
   * the caller's module (declare it as `implementation`/`runtimeOnly` in your
   * `build.gradle.kts`).
   */
  fun extractToFile(): File = extractToFile(SdkBundleResource::class.java.classLoader, cached)

  /**
   * Test-injectable variant. The classloader controls where [RESOURCE_PATH] is resolved from
   * (production passes the module's own classloader; tests can pass a stub classloader to
   * exercise the missing-resource error path). The cache reference is parameterized so a
   * test can pass a fresh [AtomicReference] and exercise the double-checked-locking idiom
   * without the production singleton's prior state.
   *
   * Marked `internal` so the test injection point doesn't leak across module boundaries —
   * `:trailblaze-scripting-subprocess` and other consumers see only [extractToFile] above.
   */
  internal fun extractToFile(classLoader: ClassLoader?, cache: AtomicReference<File?>): File {
    cache.get()?.takeIf { it.isFile }?.let { return it }
    synchronized(cache) {
      cache.get()?.takeIf { it.isFile }?.let { return it }
      val extracted = doExtract(classLoader)
      cache.set(extracted)
      return extracted
    }
  }

  private fun doExtract(classLoader: ClassLoader?): File {
    val bytes = loadBundleBytes(classLoader)
    val tempDir = Files.createTempDirectory(TEMP_DIR_PREFIX)
    tempDirsToCleanUp.add(tempDir.toFile())
    registerShutdownHook()
    val finalPath = tempDir.resolve(FILE_NAME)
    // Two-phase write: dump the bytes to a sibling `.staging` path first, then atomic-rename
    // onto `finalPath`. This makes the appearance of the final file all-or-nothing — a node
    // subprocess that opens `finalPath` either sees the complete bundle or sees nothing,
    // never a partial write. `moveAtomicallyOrFallback` handles filesystems that reject
    // ATOMIC_MOVE; see its body for why the fallback is still safe in our 700 tempDir.
    val stagingPath = tempDir.resolve("$FILE_NAME.staging")
    Files.write(stagingPath, bytes)
    moveAtomicallyOrFallback(stagingPath, finalPath)
    return finalPath.toFile()
  }

  /**
   * Reads the bundle bytes from [classLoader]'s resource path. Test injection point —
   * tests pass a stub classloader (e.g. one with no resources) to exercise the missing-
   * resource error path without un-shipping the bundle from the test classpath.
   */
  internal fun loadBundleBytes(classLoader: ClassLoader?): ByteArray {
    val resolvedClassLoader = classLoader
      ?: error(
        "trailblaze-scripting-bundle: no classloader available to load $RESOURCE_PATH. " +
          "This shouldn't happen on the host JVM — file an issue if you hit it.",
      )
    val stream = resolvedClassLoader.getResourceAsStream(RESOURCE_PATH)
      ?: error(
        "trailblaze-scripting-bundle: classpath resource $RESOURCE_PATH not found. " +
          "Add `:trailblaze-scripting-bundle` to your module's runtime classpath " +
          "(implementation or runtimeOnly) to ship the bundle alongside the SDK.",
      )
    return stream.use { it.readBytes() }
  }

  private fun moveAtomicallyOrFallback(src: Path, dst: Path) {
    try {
      Files.move(src, dst, StandardCopyOption.ATOMIC_MOVE, StandardCopyOption.REPLACE_EXISTING)
    } catch (atomicNotSupported: AtomicMoveNotSupportedException) {
      // Some layered container filesystems and a handful of network mounts reject atomic
      // moves. The non-atomic move's window for partial state is still safe here because
      // both src and dst sit inside our process-scoped 700 tempDir — no other user can
      // observe the intermediate state, and only this JVM (serialized by the synchronized
      // block in extractToFile) ever races against the rename.
      try {
        Files.move(src, dst, StandardCopyOption.REPLACE_EXISTING)
      } catch (fallback: Exception) {
        // Chain the original `AtomicMoveNotSupportedException` so a stack trace on the
        // fallback failure also surfaces "we tried atomic first, the FS rejected it".
        // Without this chaining the user sees only the second failure mode and has to
        // guess why we ended up on the non-atomic path in the first place.
        fallback.addSuppressed(atomicNotSupported)
        throw fallback
      }
    }
  }

  private fun registerShutdownHook() {
    if (!shutdownHookRegistered.compareAndSet(false, true)) return
    val hook = Thread {
      tempDirsToCleanUp.forEach { dir ->
        runCatching { dir.deleteRecursively() }
      }
    }
    // `addShutdownHook` throws `IllegalStateException` if the JVM has already entered
    // shutdown — which can happen if `extractToFile()` is invoked transitively from
    // another module's shutdown hook (rare, but possible in cleanup paths that themselves
    // touch the inline-tool runtime). Swallow it: we can't register cleanup at this point,
    // but the JVM is exiting anyway and the OS's tmp-dir reaper will eventually catch the
    // unreaped dir. CAS-flipping `shutdownHookRegistered` to true above means we won't
    // retry on the next call either, which is the right behavior — there's nothing useful
    // a retry would do.
    try {
      Runtime.getRuntime().addShutdownHook(hook)
    } catch (_: IllegalStateException) {
      // JVM already shutting down. Cleanup is the OS's problem now.
    }
  }
}
