// Minimal typed client for the Trailblaze daemon's `/rpc/<Name>` endpoints — the TypeScript twin
// of the Kotlin `HostRpcClient`. Pair it with the generated request/response types in
// `../generated/host-rpc.ts` (Kotlin-canonical, regenerated by `:trailblaze-models:generateDtoTs`).
//
// Wire contract (Kotlin side: OnDeviceRpcServer + RpcHandlerExt):
//   POST /rpc/<RequestName>  +  <Request> JSON
//     2xx     → <Response> JSON
//     non-2xx → RpcErrorResponse JSON  { errorType?, message, details? }
//
// `RpcResult` is constructed client-side from that outcome; it is NOT a wire type. The daemon's
// Kotlin `RpcResult` is unwrapped server-side (raw response on 200, flat error on non-2xx), so it
// never appears in a payload — which is why it lives here, hand-written, rather than generated.

/** Flat error envelope the daemon returns on a non-2xx RPC response. */
export interface RpcErrorResponse {
  errorType?: string | null;
  message: string;
  details?: string | null;
}

/**
 * Result of an RPC call. Discriminated on `ok`, so the compiler forces (and narrows) handling of
 * both the success and failure branches — no exceptions to forget to catch.
 */
export type RpcResult<T> =
  | { ok: true; data: T }
  | { ok: false; error: RpcErrorResponse };

export interface RpcCallOptions {
  /** Daemon origin. Defaults to `""` (same-origin, e.g. from the served web UI). */
  baseUrl?: string;
  /** Optional cancellation signal. */
  signal?: AbortSignal;
  /** Override `fetch` (for tests or non-browser runtimes). Defaults to the global `fetch`. */
  fetchImpl?: typeof fetch;
}

/**
 * Call a daemon RPC endpoint. [requestName] is the Kotlin request class's simple name — the
 * `/rpc/<Name>` path segment — e.g. `"GetConnectedDevicesRequest"`.
 *
 * Until a generated request→response registry lands, pass both type parameters explicitly:
 * ```ts
 * const r = await rpcCall<GetConnectedDevicesRequest, GetConnectedDevicesResponse>(
 *   "GetConnectedDevicesRequest", {});
 * if (r.ok) r.data.devices.forEach(...); else showError(r.error.message);
 * ```
 */
export async function rpcCall<TRequest, TResponse>(
  requestName: string,
  request: TRequest,
  options: RpcCallOptions = {},
): Promise<RpcResult<TResponse>> {
  const baseUrl = options.baseUrl ?? "";
  const doFetch = options.fetchImpl ?? fetch;

  let response: Response;
  try {
    response = await doFetch(`${baseUrl}/rpc/${requestName}`, {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(request),
      signal: options.signal,
    });
  } catch (e) {
    const message = e instanceof Error ? e.message : String(e);
    return { ok: false, error: { errorType: "NETWORK_ERROR", message } };
  }

  const body = await response.text();
  if (response.ok) {
    // An empty 2xx body is the valid "no payload" response (TResponse = void/undefined).
    if (!body) return { ok: true, data: undefined as TResponse };
    // A non-empty 2xx body must be valid JSON. If it isn't (e.g. a proxy returned plain text with
    // a 200), surface a structured failure rather than letting JSON.parse throw — the RpcResult
    // contract promises no exceptions to forget to catch. `SERIALIZATION_ERROR` mirrors the Kotlin
    // `RpcResult.ErrorType` enum (the same vocabulary the NETWORK_ERROR / HTTP_ERROR paths draw from).
    try {
      return { ok: true, data: JSON.parse(body) as TResponse };
    } catch {
      return {
        ok: false,
        error: {
          errorType: "SERIALIZATION_ERROR",
          message: "2xx response body was not valid JSON",
          details: body.slice(0, 300),
        },
      };
    }
  }

  // Non-2xx: the daemon serializes a flat RpcErrorResponse. Fall back to a synthetic one if the
  // body isn't the expected shape (e.g. a proxy returned plain text).
  let error: RpcErrorResponse;
  try {
    error = JSON.parse(body) as RpcErrorResponse;
  } catch {
    error = { errorType: "HTTP_ERROR", message: `HTTP ${response.status}`, details: body.slice(0, 300) };
  }
  return { ok: false, error };
}
